### ISSUE TITLE
summary statistics of date 

### ISSUE THREAD

**Issue by waynelapierre** [SebKrantz/collapse#109]
The collapse::qsu function currently seems to not work with dates. It would be great if qsu could summarize date (and time) variables, just like the R base summary function.

**Comment by SebKrantz** [comment]
Thanks, but I think this will not be implemented in qsu() as the standard deviation of the date is not meaningful, and I also cannot apply the formatting of print.qsu() to the date strings. I can however try to add the quantiles of the date to descr(). By the way if you have nothing to add to your previous issue, be so kind and close that one.

**Comment by waynelapierre** [comment]
Agree. For the dates, knowing the max and min values will be good enough.

**Comment by lyifa** [comment]
The data time formats in the R base and data.table are different. Not sure how collapse will handle this.

**Comment by SebKrantz** [comment]
Hi so @lyifa please create an issue if you think the data.table date format is not handled correctly. collapse just dispatches by storage type (integer, double, character) and copies the attributes later on, so it should handle all classes stored as integer, character or double. Regarding summary statistics of date, I will have to find a better solution. `descr` now computes the min and max of date but does not retain the format because it is put together with th enumber of observations into a vector. The issues I have also is that the print method `print.descr` was built to format numeric variables, and the method `as.data.frame.descr` is supposed to coerce the output of descr to a tidy data frame, and also cannot handle dates. All in all I think sufficient modification of these functions, which would include creating a list of statistics and adding another level of recursion and complexity to both print and data frame coercion methods, is not really worth the couple of use cases. I'll look at it once more, but I cannot promise anything at this point.
