### ISSUE TITLE
fsummarise warning caused by comparing on elements with different lengths

### ISSUE THREAD

**Issue by hongyuanjia** [SebKrantz/collapse#138]
I got a warning every time I run `fsummarise()`:

```
Warning message:
In as.character(ei[[1L]]) == .FAST_STAT_FUN :
  longer object length is not a multiple of shorter object length
```

Should use `%in%` instead of `==`.

https://github.com/SebKrantz/collapse/blob/5ce5a532a45a295323ad9692c24264146ea68c30/R/fsummarise.R#L27

**Comment by SebKrantz** [comment]
Hi, that’s strange because I don’t get that. Can you give a code example? And which operating system are you using?

**Comment by hongyuanjia** [comment]
Hi, below is a reprex:

``` r
`%>%` <- magrittr::`%>%`

mtcars %>% collapse::fgroup_by(cyl) %>%
  collapse::fsummarise(mean_mpg = collapse::fmax(mpg))
#> Warning in as.character(ei[[1L]]) == .FAST_STAT_FUN: longer object length is not
#> a multiple of shorter object length
#>   cyl mean_mpg
#> 1   4     33.9
#> 2   6     21.4
#> 3   8     19.2
```

<sup>Created on 2021-03-18 by the [reprex package](https://reprex.tidyverse.org) (v1.0.0)</sup>

**Comment by SebKrantz** [comment]
Ok, it’s caused by the ::, so you have 3 terms instead of 1. I will fix this in the next update. To solve it now, first check if you actually need to call collapse:: inside fsummarise. It might work without because the expression is evaluated internally. Then, if your developing a package I strongly recommend importing the collapse functions you need, for general performance considerations as there is an overhead to ::.

**Comment by hongyuanjia** [comment]
> It might work without because the expression is evaluated internally

That's true. Directly using `fmax()` works.

> Then, if your developing a package I strongly recommend importing the collapse functions you need, for general performance considerations as there is an overhead to ::.

Yes, I am trying to utilize collapse functions where possible because they are quite fast. I will import those functions when I finalize the workflow.
