### ISSUE TITLE
ftransform and fgroup_by

### ISSUE THREAD

**Issue by ggrothendieck** [SebKrantz/collapse#140]
`ftransform` does not respect `fgroup_by`.  For example, the following ignores the grouping: 

```
anscombe2 <- anscombe
anscombe2$g <- c(0L, 0L, 0L, 0L, 0L, 1L, 1L, 1L, 1L, 1L, 1L)

anscombe2 %>%
  fgroup_by(g) %>%
  ftransformv(startsWith(names(.), "y"), cumsum) %>%
  fungroup
```

As far as I can tell it is only the `fsum`, `fmean` and related functions and `fsummarise` that respect `fgroup_by`. This works but it would still be desirable that `ftransform` respect grouping as well.

```
anscombe2 %>% ftransformv(startsWith(names(.), "y"), BY, g, cumsum)
```

It is possible that there are other functions that could usefully respect `fgroup_by` as well but I haven't played with this enough to know.

**Comment by SebKrantz** [comment]
See the documentation page of `ftransform` for examples how to do grouped transformations with `ftransform`, basically you need to use the `g` and `TRA` arguments of the statistical functions collapse provides, or you use `BY` inside `ftransform`, but note that your data needs to be sorted by groups beforehand if you use `BY`. I might add a function `fmutate` at some point, but it would not add to what you can do with `ftransform` and the fast ststistical functions, but simply be more convenient and dplyr-like for some cases. My thinking so far goes that `collapse` does not need to do arbitrary computations by groups fast, that's why `BY` is written in base R and there is no `fmutate` yet or something. Why? Because you already have `dplyr` and `data.table` which are excellent fully featured split apply combine computing packages. My goal with `collapse` is to provide more speed, grouped and weighted computations, advanced time series and panel data computations, list processing, advanced summary statistics etc. that go beyond what you can do with dplyr or data.table. I'ts by no means a drop in to these packges, let alone there is no joins, no rolling statistics, no reshaping, no vectorized switches etc. My recommendation is to use data.table for aggregations and transformations you cannot do well with collapse (like applying cumsum to data by groups).

**Comment by SebKrantz** [comment]
Also look at this very similar issue and my answer: https://github.com/SebKrantz/collapse/issues/132

**Comment by ggrothendieck** [comment]
I know about BY inside ftransform.  In fact, I even provided an example of it in my post. 

The problem is that this is all highly misleading. Maybe you should get rid of fgroup_by and do it some other way or name it differently.  As you point out someone else also fell into this trap and I just corrected an SO post that used ftransform inside fgroup_by after I made the same mistake myself.  Everybody is making the same mistake.

Also related to this specific example, would it be feasible to have a fast cumsum (and maybe cumsprod) as one of the fast statistical functions oris it necessary that they return scalars like mean and sum do?

Also would it be possible to extend B to act like ave where you can specify your own function and not only work with mean?

**Comment by SebKrantz** [comment]
Hi, yeah maybe there can be fcumsum in a future release. But as I said
before I‘m not making major changes to to the package. People indeed need
to understand that this is not a split-apply-combine computing package, a
grammar of data manipulation or anything like it. I provided a behind a
small excursus in the collapse and dplyr vignette that explains how
collapse works in contrast with dplyr.

I encourage you to read that Excursus. Regarding split-apply-combine, I am
not interested in it, you have data.table which efficiently does it.
Applying an R functions to groups will always be much slower than running
grouped computations in C++. data.table does some of that optimization
internally what they call GForce. It replaces some standard functions like
the mean with gmean, an internal grouped mean in data.table. collapse only
does GForce and, apart from aggregation, is not really equipped to deal
with arbitrary R functions.

In general, I want to say I very much appreciate your inputs so far, but I
also think now you should dive deeper into the package yourself and
consider the documentation resources available. I’m a bussy person as well
and I don’t want to have a new issue every second day which is not really
an issue but just a question on how to use the package. Thanks for your
understanding.
