### ISSUE TITLE
integer groups in `fsum(..., use.g.names = FALSE)` unnecessary factor conversion?

### ISSUE THREAD

**Issue by alex-raw** [SebKrantz/collapse#148]
I have noticed that passing an integer vector as `g` in `collapse::fsum` causes internal factor conversion, even when `use.g.names = FALSE`. This is a considerable slowdown if the names are irrelevant. I have data with integer group ids already present, which I think is not an edge case.

Some test data:
```
sum_test <- function(x, g) collapse::fsum.default(x, g, use.g.names = FALSE)
x <- sample(1:1e7)
g_int <- sample(1:1000, length(x), replace = TRUE)
g_fac <- as.factor(g_int)

microbenchmark::microbenchmark(
ans1 <- sum_test(x, g_int),
ans2 <- sum_test(x, g_fac)
, times = 10L
)

                        # expr       min       lq      mean    median        uq       max neval
  # ans1 <- sum_test(x, g_int) 173.77554 180.0894 184.38943 183.61633 189.80703 192.17675    10
 # ans2 <- sum_test(x, g_fac)  37.00679  48.4336  47.61358  49.42442  50.43859  51.29969    10

identical(ans1, ans2) # TRUE
```

Here are the relevant lines in `collapse::fsum.default`
```
...
            if (use.g.names) {
              ...
            }
            if (is.nmfactor(g))
                return(.Call(Cpp_fsum, x, fnlevels(g), g, w,
                  na.rm))
            g <- qG(g, na.exclude = FALSE)
            return(.Call(Cpp_fsum, x, attr(g, "N.groups"), g,
                w, na.rm))
...
```

Adding something along the lines of
`if (is.integer(g)) return(.Call(cpp_fsum, x, fNdistinct(g), g, w, na.rm)`
could fix this. I feel like this is not intended behavior, but I lack the bigger picture. I also suspect that there are similar functions with this behavior.

**Comment by SebKrantz** [comment]
Hi, thanks. The problem with your suggested code is that it will generate empty vector spaces for unused groups. So for example if `x <- 1:4; g <- c(1:3, 5L)`, the result of `.Call(cpp_fsum, x, fNdistinct(g), g, w, na.rm)` without coercing `g` to factor is `c(1, 2, 3, NA, 5)`. So I think coercing to factor is necessary to give proper grouping functionality. I have however created the class `qG` and associated function to create a factor light class which is recognized by the fast functions. So if you have an integer vector, you can simply do 

```
attr(g_num, "N.groups") <- fNdistinct(g_num)
class(g_num) <- "qG"
```
to get what you want without incurring extra grouping cost. See `?GRP` and `?qG` for more information.

**Comment by alex-raw** [comment]
Thanks, that works just fine!
I am aware of `qG` since that's the unexpected bottleneck in my example. Still the performance hit is not intuitive at all.
But I see the problem. I guess, testing whether an unordered integer sequence is gapless would nullify much of the performance gain. And a switch like `contiguous.ids` that, if `TRUE`, does what's in your code snippet would be overkill in all the f..-functions.

How about some more basic wrappers like, `as_qG(x, ...)` and `as_qF(x, ...)` (`as.factor_qG` only converts qG to qF if I understand correctly)? They could apply some shortcuts, and deal with all the different combinations of data types, sorts, names, attributes, which could also eliminate some complexity in all those nested conditionals in the grouped functions. This is maybe where a `contiguous.ids`-option would come in handy. Maybe too niche. Just throwing out ideas. :)

**Comment by SebKrantz** [comment]
Thanks for the thoughts. Checking for seamless integer sequences for
integers passed could be an option, but I would still have to transform
them to integer sequences starting from 1 to not break the C++ code. Right
now you have qF and qG and GRP (as.factor_qG just being for conversion and
internally called by qG if passed a factor), Which create simple objects
that can be passed directly down to C++ code. Note that in the case of qF
and qG you may want to use argument na.exclude = FALSE which adds a class
„na.included“ that also circumvents a necessary call to anyNA (as missing
values in the factor will cause a segfault if not replaced with some finite
integer). GRP objects never incur further checks.

Apart from conversion methods between these objects, they are created from
integer or character vectors by general mechanisms of matching and sorting
values or radix ordering. That’s where the performance decline comes from
as these operations are expensive relative to just calculating a grouped
sum in C++. I‘m not convinced of writing additional C++ code to check if
something is a plain integer sequence, as this Would add additional costs
if it is not and I need to call a proper grouping mechanism afterwards.

I think manually creating these objects as you did and reusing them once
created is optimal for performance and gives you full control, you just
need to create integer vectors that start from 1, with the maximum integer
equal to the group count, otherwise your R session will crash.

**Comment by SebKrantz** [comment]
I'm closing this for now, but will keep thinking about it.
