### ISSUE TITLE
return 25%, 50%, and 75% quantiles with qsu

### ISSUE THREAD

**Issue by waynelapierre** [SebKrantz/collapse#159]
I could not figure out how to return 25%, 50% (median), and 75% quantiles with qsu. All I can get are N, Mean, SD, Min, Max, Skew, and Kurt. Are these quantiles available in qsu? If not, it would be great if you could add them. Thanks.

**Comment by SebKrantz** [comment]
Hi, if you want to get more statistics you can use `descr`, which also has an efficient `as.data.frame` method. `qsu` does not compute order statistics because it's based on a one-pass method. You cannot compute order statistics/quantiles in a single pass through the data, but need to apply some partial sorting which involves iterating on the data. Adding this would slow down `qsu` at least 2 times, so this will not be done. If you need fast grouped order statistics, you can use `fnth`, passing a probability to `n`. Otheriwse I suggest doing something like `rsplit(data, var ~ id) %>% lapply(quantile) %>% unlist2d("id")`, `BY(data, id, quantile, expand.wide = TRUE)`, or use data.table and do `data[, as.data.frame(descr(.SD, table = FALSE)), by = id, .SDcols = vars]`.

**Comment by waynelapierre** [comment]
thanks! I will use the descr function.
