### ISSUE TITLE
Update examples to forthcoming native pipe (`|>`)

### ISSUE THREAD

**Issue by grantmcdermott** [SebKrantz/collapse#162]
Hi Sebastian,

Just a small and likely redundant note to say that I've tested `collapse` against the forthcoming R 4.1.0 release candidate. The new native pipe (`|>`) appears to work very nicely with the package. Examples:

```r
# R Under development (unstable) (2021-05-01 r80254) -- "Unsuffered Consequences"

iris |> fgroup_by(Species) |> fNdistinct() 
#>      Species Sepal.Length Sepal.Width Petal.Length Petal.Width
#> 1     setosa           15          16            9           6
#> 2 versicolor           21          14           19           9
#> 3  virginica           21          13           20          12

w <- abs(rnorm(fnrow(iris)))
iris |> 
  add_vars(w) |> 
  fsubset(Sepal.Length < fmean(Sepal.Length), Species, Sepal.Width:w) |>
  fgroup_by(Species) |> 
  fvar(w) |> 
  roworder(sum.w) 
#>      Species     sum.w Sepal.Width Petal.Length Petal.Width
#> 1  virginica  5.876047  0.01770740   0.04656351  0.01606024
#> 2 versicolor 18.347134  0.05583887   0.14284741  0.02330951
#> 3     setosa 35.626894  0.12962384   0.03163604  0.01031945
```
When the time comes, it might be worth updating the doc examples that currently rely on the magrittr pipe (`%>%`), since that's one less additional package/dependency to worry about.

**Comment by SebKrantz** [comment]
Thanks Grant, that's good to know. I'll think about updating the examples. I must say I like the `x %>% f` better than `x |> f()`, and the other pipes in matrittr are very useful as well. I'm also working on a framework package similar to the tidyverse, and I want magrittr to be part of it, so from that perspective I'm not sure if it's really worth it because that base pipe for me does not replace a lot of things I can currently do with magrittr. But will see when the time comes. At least the speed of the base pipe is second to none.

**Comment by grantmcdermott** [comment]
Certainly, all fair enough. I'm happy to close and just wanted to let you know in case it's of interest. 

I really like what you've done with `collapse` and I'm interested to see your new framework package when it comes out!
