### ISSUE TITLE
matrix attribute

### ISSUE THREAD

**Issue by ggrothendieck** [SebKrantz/collapse#163]
If one displays the result of `flag`  it shows a matrix attribute but if one uses `matrix` it does not. This may be the result of changes in R.  Note below how the class does not display when we use `matrix` below but does when we use `flag`.  (Examing the `dput` of the outputs can be used to show the differences.)

```
> flag(1:5, 2:3)
     L2 L3
[1,] NA NA
[2,] NA NA
[3,]  1 NA
[4,]  2  1
[5,]  3  2
attr(,"class")   <-------------------
[1] "matrix"

> matrix(1, 3, 3)
     [,1] [,2] [,3]
[1,]    1    1    1
[2,]    1    1    1
[3,]    1    1    1

> packageVersion("collapse")
[1] ‘1.5.3’

> R.version.string
[1] "R version 4.1.0 RC (2021-05-16 r80303)"
```

**Comment by SebKrantz** [comment]
Hi, so this was actually done on purpose a few versions ago, to make sure that if you have something like `fdiff(flag(x, 1:2))`, `fdiff.matrix` is called on the lag matrix. With `x` a plain vector this would work even without the matrix class attached, but if `x` is a 'ts' object, then `fdiff.default` would be called (because the 'ts' class is preserved and no 'matrix' class is attached). It turns out that with 'xts' time series you have just that problem that thex have classes 'xts' and 'zoo' but no matrix class. That's why for collapse 1.5.0 I added code to the default methods that checks if an object passed is actually a matrix, and have the default method call the matrix method if this is the case. So as far as collapse is concerned, the added matrix class is now redundant, but I think it still could make sence for other functions you might want to apply to, say, a lag matrix from a 'ts' object, so my thinking so far is that it is better to be kept than not. Can you give me examples where it is problematic to have the matrix class?

**Comment by ggrothendieck** [comment]
I don't recall the specific example that motivated this but it could have an effect on S3 methods. At some point R changed the class of matrices to c("matrix", "array") so presumably the result in collapse should be that class vector too and not just "matrix".

```
b <- as.matrix(BOD)
class(b)
## [1] "matrix" "array" 
```

**Comment by SebKrantz** [comment]
It is right that `class` now returns a class `c("matrix", "array")`, but this is the implicit class of the object (just as `class(1:10)` returns `"integer"`). Let `m <- as.matrix(mtcars)`, then `class(m)` is `c("matrix", "array")`, but `oldClass(m)` is `NULL`, `attributes(m)` shows no class attribute and `is.object(m)` is `FALSE`. Thus the matrix in R is still identified by the `dim` attribute, not the class. I have chnaged the collapse code towards that end `flag(1:10, 1:2)` now has a `dim` attribute but no class. However if `is.object(x)` is true, such as `flag(AirPassengers, 1:2)`. a class `matrix` is added. This is also consistent with R, a matrix time series like `EuStockMarkets` has classes `c("mts", "ts", "matrix")`. I do not add a class `"mts"` here because `x` could be something a different time series class than 'ts' and a lag matrix is not strictly a multivariate series. So collapse 1.6.0, just published yesterday, is now very much in line with base R. By the way it also facilitates programming w.g. with `fgroup_by` which I think you requested earlier.
