### ISSUE TITLE
No "ss<-" function: Alternatives or suggestions?

### ISSUE THREAD

**Issue by Sheksta** [SebKrantz/collapse#176]
Dear Seb,

Thanks for a super useful package. It's saved me a lot of time.

Here's a point where I am stuck in trying to employ _collapse's_ functions to make my code faster. How do I replace a subset of a dataframe (speed being priority)?

I've racked my head against a wall for a few days now, and can't seem to find a way to do this using the functions provided in _collapse_. 

For example, `Big_DF[logical_indexes] <- Little_DF`

Would you have any input towards this issue? 

Would kindly appreciate your input if possible. 

Many thanks,
Abhishek.

**Comment by SebKrantz** [comment]
Hi Abhishek, good to head you are finding collapse useful. I am sorry to keep you up with this, but you are right, there is no function in collapse for that at the moment, and I am not sure there will be one because `data.table::set` is an excellent solution to this. First, if you just transform columns you can do that with `get_vars<-` or `settransform` in collapse:

``` r
library(collapse)
Big_DF <- GGDC10S

# If we just want to transform data it is easy:
logical_indices <- fselect(GGDC10S, AGR:SUM, return = "logical")
Little_DF <- STD(GGDC10S, cols = logical_indices, stub = FALSE) # Standardizing columns
get_vars(Big_DF, logical_indices) <- Little_DF

# Or do it in one go:
settransformv(Big_DF, logical_indices, STD)
```
But I presume you meant replacing rows: 
``` r
col_indices <- which(logical_indices)
logical_indices <- with(Big_DF, Variable == "VA")

# Lets say I calculate some growth rates on the subset
Little_DF <- GGDC10S |> ss(logical_indices) |> 
  G(by = ~ Country, t = ~ Year, cols = col_indices, keep.ids = FALSE, stubs = FALSE)

# I can use base R or data.table to do this:
integer_indices <- which(logical_indices) # Need integer indices for data.table::set
microbenchmark::microbenchmark(base = Big_DF[integer_indices, col_indices] <- Little_DF, 
                               data.table = data.table::set(Big_DF, integer_indices, col_indices, Little_DF))
#> Unit: microseconds
#>        expr     min       lq      mean median       uq      max neval cld
#>        base 313.712 437.0995 504.37550 467.89 509.8375 3647.624   100   b
#>  data.table  43.286  44.4015  55.79455  49.98  59.7975  166.450   100  a
```

<sup>Created on 2021-07-12 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
 
Note that `data.table::set` does not convert you data frame into a data table. Also note that in general using integer indices in R is faster than logical indices, because with integers R already knows the length it has to replace, whereas with logicals you need an additional pass (which is done in the C code underlying base R) to count the number of `TRUE` to know your replacement length.

**Comment by Sheksta** [comment]
Thanks Seb, I appreciate the write-up of alternative methods like data.table 👍

**Comment by Sheksta** [comment]
Personally, I believe it would be better to include an error message that is more informative and provides resources to data.table's set() function. Users of this package could wonder why there is a "get_vars()<-" but no "ss()<-".

**Comment by SebKrantz** [comment]
Hello Abhishek, thanks, yes I could include a reference to `set` in a future release.
