### ISSUE TITLE
doc variable.wise in ?fhdbetween

### ISSUE THREAD

**Issue by tappek** [SebKrantz/collapse#181]
In `?fhdbetween` we have:

> variable.wise	    data.frame methods: Setting variable.wise = TRUE will process each column individually i.e. use all non-missing cases in each column and in fl (fl is only checked for missing values if na.rm = TRUE). [...]

-> this argument is available for **p**data.frames as well, so I suggest to start explanation with "(p)data.frame methods ...".

I would find `column.wise` a more intutive name as it expresses what it is about (and may be closer to a programming/data structure point of view. However, statisticans like to put their "variables" (in general, that is a very broad term) into columns of matrices/data frames).

**Comment by SebKrantz** [comment]
Thanks Kevin. I have adopted "(p)data.frame", and I agree possibly column.wise would be better, but at this stage of development I wont't rename an argument just because another name would be better. This would require keeping the old name in the function for around 2 years and I don't think it's worth it.
