### ISSUE TITLE
flag produces object of non-sane class c(["pseries]", "factor", "matrix") for factor input and n > 1

### ISSUE THREAD

**Issue by tappek** [SebKrantz/collapse#183]
I noticed `flag` produces likely an ill-classed return value for factor input and n > 1, see example below.

I think `c("factor", "matrix")` is not a valid class (albeit `is.factor` says so for the return object). Another thing is that a matrix is always an array per class attribute as well since a while in R.
The return value shares some properties of a factor but is likely not valid (see also [this post on SO](https://stackoverflow.com/questions/28723059/can-we-get-factor-matrices-in-r)). 

Man page for `flag` under Details first mentions atomic vectors (which excludes factors) and a little later "x can be of any standard data type" where the latter gives the somewhat unexpected result for a factor.

`plm::lag` behaves as base R when `matrix`  and `factor` collide: coerce the factor to character and put in matrix (rending the result somewhat unusable). For `flag`s pseries method, class is  "pseries" "factor"  "matrix" which is not considered a pseries by the plm package (albeit `is.pseries` tells us otherwise for this object).

I did not check the other methods.

    library(collapse) # 1.6.5
    library(plm)
    data("Grunfeld", package = "plm")

    Grunfeld$fac <- factor(c(200:2, 1))
    pGrunfeld <- pdata.frame(Grunfeld)

    # default method
    class(cfld <- collapse::flag(Grunfeld$fac, n = 2:3)) # "factor"  "matrix" 
    is.factor(cfld) # TRUE, checks via inherits()
    # pseries method
    class(cflp <- collapse::flag(pGrunfeld$fac, n = 2:3)) # "pseries" "factor"  "matrix" 
    class(flp <- plm::lag(pGrunfeld$fac, k = 2:3)) # "matrix" "array"`

**Comment by SebKrantz** [comment]
Hi Kevin, thanks for this. I could add a class `"array"` to make it consistent with base R, but as you say there is not much you can do with a factor matrix in base R. `"collapse"` can however handle factor matrices without problems. To the C-code this is simply an integer matrix with some attributes attached. The `"matrix"` class is there so that functions can be nested. e.g. 

``` r
f <- iris$Species
dim(f) <- c(50, 3)
str(f)
#>  Factor[1:50, 1:3] w/ 3 levels "setosa","versicolor",..: 1 1 1 1 1 1 1 1 1 1 ...
is.matrix(f)
#> [1] TRUE
head(f)
#>      [,1]   [,2]       [,3]     
#> [1,] setosa versicolor virginica
#> [2,] setosa versicolor virginica
#> [3,] setosa versicolor virginica
#> [4,] setosa versicolor virginica
#> [5,] setosa versicolor virginica
#> [6,] setosa versicolor virginica
#> Levels: setosa versicolor virginica
f[1:2, -3]
#>      [,1]   [,2]      
#> [1,] setosa versicolor
#> [2,] setosa versicolor
#> Levels: setosa versicolor virginica

library(collapse)
#> collapse 1.6.5, see ?`collapse-package` or ?`collapse-documentation`
#> Note: stats::D  ->  D.expression, D.call, D.name
#> 
#> Attaching package: 'collapse'
#> The following object is masked from 'package:stats':
#> 
#>     D
head(flag(f, -1:1))
#>      [,1]   [,2]   [,3]   [,4]       [,5]       [,6]       [,7]      [,8]     
#> [1,] setosa setosa <NA>   versicolor versicolor <NA>       virginica virginica
#> [2,] setosa setosa setosa versicolor versicolor versicolor virginica virginica
#> [3,] setosa setosa setosa versicolor versicolor versicolor virginica virginica
#> [4,] setosa setosa setosa versicolor versicolor versicolor virginica virginica
#> [5,] setosa setosa setosa versicolor versicolor versicolor virginica virginica
#> [6,] setosa setosa setosa versicolor versicolor versicolor virginica virginica
#>      [,9]     
#> [1,] <NA>     
#> [2,] virginica
#> [3,] virginica
#> [4,] virginica
#> [5,] virginica
#> [6,] virginica
#> Levels: setosa versicolor virginica

head(flag(flag(iris$Species, -1:1)))
#>      F1     --     L1    
#> [1,] <NA>   <NA>   <NA>  
#> [2,] setosa setosa <NA>  
#> [3,] setosa setosa setosa
#> [4,] setosa setosa setosa
#> [5,] setosa setosa setosa
#> [6,] setosa setosa setosa
#> Levels: setosa versicolor virginica
```

<sup>Created on 2021-08-24 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

I don't see why this would be problematic, or why one would need to do an inefficient coercion to character. I also don't see why anyone would require computing multiple lags on a factor variable. So maybe you can explain further to me what the concrete concerns with `plm` are e.g. why is this worse than creating a character matrix?

**Comment by tappek** [comment]
I wasn't sure if this is intentional. Also, I was wondering whether it is a good idea to diverge from base R definitions of some basic classes.  At some point this could cause trouble. I had to try a few basic function and then found an example with `dim()`, continuing my initial example:

```
dim(cfld) # 200 2
class(cfld[4, 2]) # "factor" "matrix"
dim(cfld[4, 2]) # NULL
```
The loss of the attribute `dim` could be easily fixed in the subsetting, though.

I understand that it can be desirable and convenient to have a factor matrix but maybe it should get its own class definition then (e.g., `c("factormatrix", "matrix", "array")`)?

My little concern with `plm` is that `flag` produces something which claims to be a pseries but it is none in the sense of the package (while admitting a pseries is not very well defined but I think of as staying one-dimensional as the its basis (either a vector or a factor) (one-dimensional not in the sense of `dim()` as that is NULL for vectors and factors)).

**Comment by SebKrantz** [comment]
Thanks Kevin! I think these concerns are all good an valid. As mentioned in an earlier e-mail, my main motivation for this is to enable nesting of computations in pseries e.g.
```
library(plm)
library(collapse)
pwld <- pdata.frame(wlddev, index = .c(iso3c, year))
plm(Dlog(PCGDP) ~ L(Dlog(LIFEEX), 0:3), pwld) # Lags of the log-difference
plm(Dlog(PCGDP) ~ Dlog(L(LIFEEX, 0:3)), pwld) # Same thing
plm(Dlog(PCGDP) ~ L(Dlog(LIFEEX, c(1, 10)), 0:3), pwld) # 1 and 10-year lagged differences
plm(Dlog(PCGDP) ~ Dlog(L(LIFEEX, 0:3), c(1, 10)), pwld) # again same thing
# Using only PLM
plm(diff(log(PCGDP)) ~ lag(diff(log(LIFEEX)), 0:3), pwld) # Lags of the difference
plm(diff(log(PCGDP)) ~ diff(log(lag(LIFEEX, 0:3))), pwld) # Error
plm(diff(log(PCGDP)) ~ lag(diff(log(LIFEEX), c(1, 10)), 0:3), pwld) # Error
```
It's not that these examples are particularly sensible or necessary, It's just that this is possible since `collapse` functions support matrices as well. So I think the mere fact that something exists which could be useful in some cases but is eventually at odds with base R and plm classes - when used outside a proper context like the one shown here - does not necessarily make it bad for me. But I understand that this could couse problems in internal code. So for now my suggestion is to move ahead with the wrapper functions around `flag.default`, and unclass the `pseries` before calling `flag.default` (or calling `qM` on the result). I will see what can be done in terms of implementation. The thing is that `flag` is generic, it preserves attributes (including the class) no matter whether you have a pseries or time-series or soemthing else. This makes for simple C++ code. I'll see if adding an exception for plm to the C++ code makes sense. I would prefer though if matrix pseries would be come a possibility.

**Comment by SebKrantz** [comment]
So I now adjusted my plm methods to do computations as in plm for `shift = "time"` (i.e. using the levels of the time factor if it can be coerced to integer). I also made sure that the plm methods to not generate a factor matrix, but instead coerce it to character. I did not adjust the methods insofar as making it impossiple to generate a pseries matrix, because I find that useful to be able to do nested computations, and also for backwards compatibility. I also did not adjust my naming conventions for lags and differences e.g. "L1", "L2", "D1", "L2D1", "L2D2" etc. because I find them clearer. If you want to use the methods following the upcoming release of collapse 1.7.0, I suggest to use the following wrapper around the methods to ensure equivalence. The methods currently don't support `shift = "row"` (which I think is redundant for all practical purposes), but of course you can simple make your own wrapper around `flag.default` as I have shown in the file attached to my e-mail from 3rd of August. 
 
``` r
library(collapsedev17)
#> collapse 1.7.0.9000, see ?`collapse-package` or ?`collapse-documentation`
library(plm)

collapse2plm_lag_diff <- function(x) {
  if(is.matrix(x)) {
    class(x) <- NULL
    attr(x, "index") <- NULL
    dimnames(x)[[2L]] <- sub("D1", "", sub("L|D", "", dimnames(x)[[2L]]), fixed = TRUE)
  }
  x
}

data("Grunfeld", package = "plm")
obs_3rd <- 3 + 20*c(0:9)
Grunfeld_wo_1937 <- pdata.frame(Grunfeld[-obs_3rd, ])

# Here the results are identical, even without collapse2plm_lag_diff()
head(lag(Grunfeld_wo_1937$inv))
#> 1-1935 1-1936 1-1938 1-1939 1-1940 1-1941 
#>     NA  317.6     NA  257.7  330.8  461.2
head(flag(Grunfeld_wo_1937$inv))
#> 1-1935 1-1936 1-1938 1-1939 1-1940 1-1941 
#>     NA  317.6     NA  257.7  330.8  461.2
identical(lag(Grunfeld_wo_1937$inv), flag(Grunfeld_wo_1937$inv))
#> [1] TRUE

# For multiple lags, need to use collapse2plm_lag_diff() to reach equivalence
head(lag(Grunfeld_wo_1937$inv, 1:3))
#>            1     2     3
#> 1-1935    NA    NA    NA
#> 1-1936 317.6    NA    NA
#> 1-1938    NA 391.8 317.6
#> 1-1939 257.7    NA 391.8
#> 1-1940 330.8 257.7    NA
#> 1-1941 461.2 330.8 257.7
head(collapse2plm_lag_diff(flag(Grunfeld_wo_1937$inv, 1:3)))
#>            1     2     3
#> 1-1935    NA    NA    NA
#> 1-1936 317.6    NA    NA
#> 1-1938    NA 391.8 317.6
#> 1-1939 257.7    NA 391.8
#> 1-1940 330.8 257.7    NA
#> 1-1941 461.2 330.8 257.7
identical(lag(Grunfeld_wo_1937$inv, 1:3), collapse2plm_lag_diff(flag(Grunfeld_wo_1937$inv, 1:3)))
#> [1] TRUE

# Same for differences...
head(diff(Grunfeld_wo_1937$inv))
#> 1-1935 1-1936 1-1938 1-1939 1-1940 1-1941 
#>     NA   74.2     NA   73.1  130.4   50.8
head(fdiff(Grunfeld_wo_1937$inv))
#> 1-1935 1-1936 1-1938 1-1939 1-1940 1-1941 
#>     NA   74.2     NA   73.1  130.4   50.8
identical(diff(Grunfeld_wo_1937$inv), fdiff(Grunfeld_wo_1937$inv))
#> [1] TRUE

head(diff(Grunfeld_wo_1937$inv, 1:3))
#>            1      2     3
#> 1-1935    NA     NA    NA
#> 1-1936  74.2     NA    NA
#> 1-1938    NA -134.1 -59.9
#> 1-1939  73.1     NA -61.0
#> 1-1940 130.4  203.5    NA
#> 1-1941  50.8  181.2 254.3
head(collapse2plm_lag_diff(fdiff(Grunfeld_wo_1937$inv, 1:3)))
#>            1      2     3
#> 1-1935    NA     NA    NA
#> 1-1936  74.2     NA    NA
#> 1-1938    NA -134.1 -59.9
#> 1-1939  73.1     NA -61.0
#> 1-1940 130.4  203.5    NA
#> 1-1941  50.8  181.2 254.3
identical(diff(Grunfeld_wo_1937$inv, 1:3), collapse2plm_lag_diff(fdiff(Grunfeld_wo_1937$inv, 1:3)))
#> [1] TRUE
```

<sup>Created on 2021-12-30 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>
