### ISSUE TITLE
Is this expected behavior from fselect

### ISSUE THREAD

**Issue by statquant** [SebKrantz/collapse#221]
Hello when doing the following you get an error
```
fselect(data.table(x=1:2, y=1:2), X = x, x = y)
Error in fselect(data.table(x = 1:2, y = 1:2), X = x, x = y) :
  object 'y' not found
```
is it the expected behavior ?
Given the `?fselect` 
```
fselect(wlddev, Country = country, Year = year
```
I would have expected this to work, not sure how it is possible to disambiguate x in the signature and x as a column name.
As a side note I do not get the point of having `fselect` and `get_vars` (as well as 2 aliases `gv`, `gvr`, this should be left to the user to do)

**Comment by SebKrantz** [comment]
Thanks, the problem is simply that the principal argument of `fselect` is called `x` and you are assigning `x` to `y`which doesn't yet exist. It's the reason all arguments in tidyverse packages start with a `.` e.g. `.data` etc. (which I did not consider when I first added the function). I will rename `x` to `.x` in the next release (since the first argument is generally not set explicitly), but the `return` argument will have to remain, so you can also not do `return = col`. 

`get_vars` is easier because it does not evaluate it's arguments within the data frame environment, and you can simply select columns with indices, character column names, logical vectors or a selector function e.g. `is.atomic`. 

`slt`is a shorthand for `fselect`, `gv` for `get_vars` and `gvr` from `get_vars(..., regex = TRUE)`.  I simply created those because I am lazy and I come from a programming environment (STATA) where it is possible to abbreviate function names.

**Comment by statquant** [comment]
You might not need to change the API, realistically x being a column name will never be called as the first argument.
I mean the following cases should represent 99.9999999% of use cases
`fselect(data, x)`
`fselect(x = data, x)`
`fselect(x = data, x = y)`
so it should be possible to disambiguate with the help of quoting no ?

Also I think `fselect` could be doing all of what's it is doing without having the need of defining `regex =`, as done in https://hope-data-science.github.io/tidyft/reference/select.html for instance

**Comment by SebKrantz** [comment]
I think we are on the same page but I'm not exaclty sure, so here is a reprex
``` r
fun <- function(x, ...) x
fun(mtcars, x = 2)
#> [1] 2
fun(mtcars, x = cyl)
#> Error in fun(mtcars, x = cyl): object 'cyl' not found
```

<sup>Created on 2022-02-04 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

If the first argument is called `x`, I cannot have any `x = ...` in the function call. The only thing I can do is rename `x` to `.x`in the next release, which I hink is a sensible thing to do, because nobody would invoke `x`explicitly to refer to the data. 

Regarding `fselect` and `get_vars`, `get_vars` existed long before `fselect`. I only started much later implementing faster versions of tidyverse functions. Of course `fselect`could be more general, but I very much like the idea of having simple functions for simple and specific purposes, also because that ensures performance. Furthermore, having NSE functions also support standard evaluation is always a complicated business, and I don't want  to get into it too deeply (just look at what they require in terms of new kinds of expressions (quosures), lazy eval etc. to make that happen, how that complicates R, and what that does to the basic execution speeds of tidyverse functions. Not my sort of business).

**Comment by SebKrantz** [comment]
I've now implemented this first argument renaming in all relevant functions, so the arguments start with a ".". I believe this is better in the long term and nobody specifies the first argument explicitly anyway. You can install the development version from Github if you like.
