### ISSUE TITLE
working with `dplyr::group_split()`

### ISSUE THREAD

**Issue by h-a-graham** [SebKrantz/collapse#230]
Hey, 
Firstly, thanks for this awesome package! 
I've run into an issue with using dplyr::group_split -  is there a way to make this work with the groups generated with {collapse}?
See below for a reprex, many thanks!
``` r
suppressMessages(library(dplyr))
options(collapse_mask='manip')
suppressMessages(library(collapse))


GGDC10S %>% 
  group_by(Country) %>%
  group_split()
#> Error: The `groups` attribute is not a data frame with its last column called `.rows`.
```

<sup>Created on 2022-02-15 by the [reprex package](https://reprex.tidyverse.org) (v2.0.0)</sup>

**Comment by SebKrantz** [comment]
Hi, you can use 

```
GGDC10S %>% 
    group_by(Country) %>%
    rsplit(GRP(.), flatten = TRUE, use.names = FALSE)
```
`flatten = TRUE` is only necessary if you have multiple groups, otherwise you get a nested list. Note in general `collapse` is not a `dplyr` clone (and doesn't aspire to be one either). So you'll have to learn the API if you want to go beyond simple things. The [documentation](https://sebkrantz.github.io/collapse/reference/index.html) is a good place to start.

**Comment by h-a-graham** [comment]
Thanks so much for the fast response. That's great and does just what I need. much appreciated. And I appreciate what you're saying re. not being a clone of dplyr - I had made a fair few assumptions about what was going on. Thanks again.
