### ISSUE TITLE
Error "lag-length exceeds average group-size": should drop levels first?

### ISSUE THREAD

**Issue by MatthieuStigler** [SebKrantz/collapse#25]
Thanks for the package!

Subsetting a dataset on a factor variable will throw an error with `L`, as it seems group size is computed for missing factors too, and hence throws zero? Maybe use `dropLevels` first?

``` r
library(collapse)
#> collapse 1.1.0, see ?`collapse-package` or ?`collapse-documentation`
#> 
#> Attaching package: 'collapse'
#> The following object is masked from 'package:stats':
#> 
#>     D
data(wlddev)

wlddev2 <- subset(wlddev, iso3c %in% c("ALB", "AFG", "DZA"))
wlddev3 <- droplevels(wlddev2)

head(L(wlddev, 1, ~iso3c, ~year, cols="LIFEEX"))
#>   iso3c year L1.LIFEEX
#> 1   AFG 1960        NA
#> 2   AFG 1961    32.292
#> 3   AFG 1962    32.742
#> 4   AFG 1963    33.185
#> 5   AFG 1964    33.624
#> 6   AFG 1965    34.060
head(L(wlddev2, 1, ~iso3c, ~year, cols="LIFEEX"))
#> Error in L.data.frame(wlddev2, 1, ~iso3c, ~year, cols = "LIFEEX"): lag-length exceeds average group-size (0)
head(L(wlddev3, 1, ~iso3c, ~year, cols="LIFEEX"))
#>   iso3c year L1.LIFEEX
#> 1   AFG 1960        NA
#> 2   AFG 1961    32.292
#> 3   AFG 1962    32.742
#> 4   AFG 1963    33.185
#> 5   AFG 1964    33.624
#> 6   AFG 1965    34.060
```

<sup>Created on 2020-05-03 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by SebKrantz** [comment]
Hi Matthieu, 

thanks for your interest in this package. The issue arises because `iso3c` is a factor and `collapse` does not perform any checks on factors apart from a necessary missing value check (which can also be skipped if you generate factors using `qF(x, na.exclude = FALSE)`). See `collapse:::is.nmfactor`, this is all I do to check factors.  

So the factor goes directly to C++ code. A group vector of size `nlevels(iso3c)` = 216 is created, and because `nrow(subset(wlddev, iso3c %in% c("ALB", "AFG", "DZA"))) / nlevels(iso3c) < n` with `n = 1` the lag length in your case, an error is provided. Using `droplevels` could of course be a solution, but I don't think I'll implement it because it would take away too much speed on large data, and speed is a top priority for this package.

So I'll think about it for a bit. The least I can do is put a note into the documentation and perhaps improve the error messages.  Another solution could be calling a GRP() on factors again, also with a performance cost. The best solution to me however seems if people just learn to drop unused factor levels. 

To your problem, a simple solution would be `L(wlddev2, 1, LIFEEX~country, ~year)`.

**Comment by MatthieuStigler** [comment]
Hi Sebastian

Oh I see, yes I am not sure about the computational cost of `dropLevels` indeed. Maybe a possibility would be to (re)use something like `dplyr::n_distinct()`, which is supposed to be quite fast, and would avoid unnecessary computaitons due to using nlevels instead?

Anyway, it seems the code is computing group sizes? Since a group size of 0 is an artifact of factors, maybe group of size zero can be safely discarded for the computation?

**Comment by SebKrantz** [comment]
Actually I think in this case just turning the error into a warning seems to be an appropriate solution as allocating a vector with too many groups does not seem to break any part of the code. I will check it this evening. Btw. `collapse::fNdistinct` seems to be the fastest distinct value count in R.
