### ISSUE TITLE
Creation of new variables using data.table `:=` operator causes warning following aggregation with `collapse` package

### ISSUE THREAD

**Issue by vinhdizzo** [SebKrantz/collapse#319]
Hi,

I'm using `collapse` version 1.8.8 (CRAN) and the [dev](https://rdatatable.gitlab.io/data.table/) version of `data.table` (1.14.3).  It appears `data.table` is throwing a warning message for `data.table` objects created by the `collapse` package.  Here is a reproducible example:

```r
library(data.table)
library(collapse)
library(magrittr)

iris_dt <- as.data.table(iris)
iris_dt2 <- iris_dt %>% fgroup_by('Species') %>% get_vars(c('Sepal.Width', 'Sepal.Length')) %>% fsum

# where warning comes up
iris_dt2[, x:=1]
```

Here is the warning message:
```
Warning message:
Invalid .internal.selfref detected and fixed by taking a (shallow) copy of the data.table so that := can add this new column by reference. At an earlier point, this data.table has been copied by R (or was created manually using structure() or similar). Avoid names<- and attr<- which in R currently (and oddly) may copy the whole data.table. Use set* syntax instead to avoid copying: ?set, ?setnames and ?setattr. If this message doesn't help, please report your use case to the data.table issue tracker so the root cause can be fixed or this message improved. 
```

Although not an error, I am adding code from `collapse` and `data.table` in my R package, and right now I have to wrap calls around `suppressWarnings` so users aren't disturbed.  Wanted to bring this to your attention in case it is fixable.  Thank you!

**Comment by SebKrantz** [comment]
Hi, so the issue with {data.table} is that a data.table object is a list with extra (hidden) elements/columns to be able to add columns by reference with `:=` without shallow-copying the list/table. This is not the way R works, when you manipulate lists or list-based objects like data frames in R, these objects are shallow copied and given exactly the required amount of columns. So you will get this issue with any R package that attempts to manipulate data.table's without importing data.table itself and relying on the methods provided in data.table, simply because all other software does not 'overallocate'.  

That being said, {collapse} has copied some C code from {data.table} to shallow copy data.tables the way {data.table} does (adding 100 hidden columns), but this code only applies inside data manipulation functions like `collap()`, `fgroup_by()` or `fsummarise()`, not inside the statistical functions. This is a deliberate choice by me, since overallocating tables is a bit more expensive (we generate 100 extra list elements which we mostly don't need every time the data.table passes through some function). You however always have the option to passs any data.frame/list through `qDT()`, which very efficiently creates a valid overallocated data.table. So this all means the following:

``` r
library(data.table)
library(collapse)
library(magrittr)

iris_dt <- qDT(iris)
iris_dt2 <- iris_dt %>% fgroup_by(Species) %>% fselect(Sepal.Width, Sepal.Length) %>% fsum()
# where warning comes up
iris_dt2[, x:=1]
#> Warning in `[.data.table`(iris_dt2, , `:=`(x, 1)): Invalid .internal.selfref
#> detected and fixed by taking a (shallow) copy of the data.table so that :=
#> can add this new column by reference. At an earlier point, this data.table
#> has been copied by R (or was created manually using structure() or similar).
#> Avoid names<- and attr<- which in R currently (and oddly) may copy the whole
#> data.table. Use set* syntax instead to avoid copying: ?set, ?setnames and ?
#> setattr. If this message doesn't help, please report your use case to the
#> data.table issue tracker so the root cause can be fixed or this message
#> improved.

iris_dt3 <- iris_dt %>% fgroup_by(Species) %>% fsummarise(across(c(Sepal.Width, Sepal.Length), fsum))
# No problem
iris_dt3[, x:=1]

iris_dt4 <- iris_dt %>% collap(Sepal.Width + Sepal.Length ~ Species, fsum)
# No problem
iris_dt4[, x:=1]

iris_dt5 <- iris_dt %>% fgroup_by(Species) %>% fselect(Sepal.Width, Sepal.Length) %>% fsum() %>% qDT()
# No problem: qDT() very efficiently creates a proper overallocated data.table
iris_dt5[, x:=1]
```

<sup>Created on 2022-09-16 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

In general, if you don't need to use {data.table} in package code, I recommend using collapse with data.frames (a tiny bit faster for the aforementioned reason), and use the converters `qDT()` or `qTBL()` to turn the result into data.table or tibble. 

I hope this is clear. It's complex, but {data.table} was created more than 10-years ago at a time when base R used to deep-copy all objects for any operation, which has changed massively since then (R has become many times more efficient), but at the time overallocating tables was a good design choice to enable {data.table} to be memory efficient.

**Comment by vinhdizzo** [comment]
Thanks @SebKrantz for the detailed explanations, and for the various suggestions.  I most likely will go the `qDT` after `fsum` path.  I can't use `collapse` exclusively without `data.table`, since after the initial aggregation, I have to do a lot of post-aggregation calculations that leverage functions like `fcase`...just easier with `data.table`.
