### ISSUE TITLE
Error using dplyr slice() with fgroup_by()

### ISSUE THREAD

**Issue by docfleetwood** [SebKrantz/collapse#353]
When I try to use the dplyr slice() command after grouping with fgroup_by(), I receive the following error,

Error in `as_tibble()`:
! `.data` must be a valid <grouped_df> object.
Caused by error in `validate_grouped_df()`:
! The `groups` attribute must be a data frame.

It does not matter what data I am using. Here is a simple example...

iris %>% fgroup_by(Species) %>% slice(1)

Yes, ffirst() works for this specific example, but I like the fact that slice() could take any number inside the (). It seems that fgroup_by keeps the class "grouped_df", so I thought the above command should work.

**Comment by SebKrantz** [comment]
Hi, thanks, but the compatibility between collapse and dplyr is such that collapse functions such as ffirst() work on a grouped_df created with dplyr::group_by(), but dplyr functions don't work on collapse grouped frames. I had to choose a different grouping object to make high speed (vectorized) grouped operations possible in collapse. collapse grouped frames inherit from grouped_df so that I don't need to create an extra method for all the statistical functions.

**Comment by docfleetwood** [comment]
Thanks for the information. I figured that I probably just misunderstood how the situation works.
Thanks for your hard work and Happy New Year!
