### ISSUE TITLE
Memory issue with `funique()`

### ISSUE THREAD

**Issue by NicChr** [SebKrantz/collapse#381]
Hi, I noticed that there's memory issues in certain circumstances when using qGs and `funique()`.
Please see the example below.

``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
library(nycflights13)

flights2 <- flights %>%
  select(origin, dest, tailnum) %>%
  mutate(group_id = group_indices(group_by(., pick(everything()))))

flights2 %>%
  collapse::funique()
#> # A tibble: 52,783 x 4
#>    origin dest  tailnum group_id
#>    <chr>  <chr> <chr>      <int>
#>  1 EWR    IAH   N14228      9903
#>  2 LGA    IAH   N24211     45557
#>  3 JFK    MIA   N619AA     32678
#>  4 JFK    BQN   N804JB     26444
#>  5 LGA    ATL   N668DN     40202
#>  6 EWR    ORD   N39463     16237
#>  7 EWR    FLL   N516JB      8307
#>  8 LGA    IAD   N829AS     45445
#>  9 JFK    MCO   N593JB     32076
#> 10 LGA    ORD   N3ALAA     48896
#> # ... with 52,773 more rows

flights2 %>%
  mutate(group_id = collapse::qG(group_id)) %>%
  collapse::funique()
#> Error in switchGRP(if (is.null(cols)) x else colsubset(x, cols), starts = TRUE, : 'Calloc' could not allocate memory (18446744072200681472 of 4 bytes)
```

<sup>Created on 2023-02-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

Thanks,
Nick

**Comment by SebKrantz** [comment]
Thanks, this was due to a C-level test having a too small data type. To explain the issue: `funique()`, where the workhorse function is `group()`, determines the number of unique values after every column passed through. If a `qG` object is encountered, it knows that the column is already grouped, and if "number of groups in qG object * number of unique values thus far < 3 * number of rows", then  *collapse* simply creates a vector of size "number of groups  in qG object * number of unique values thus far" and counts occurrences there, without hashing the data at all. The problem here was simply that this test was done with integers so the test did not fail because of integer overflows. It should have failed because "number of groups  in qG object * number of unique values thus far" is much larger than "3 * number of rows" in your case, leading to the memory allocation error. The issue has now been fixed in the GitHub / R-universe version.
