### ISSUE TITLE
collap strips Date class

### ISSUE THREAD

**Issue by ggrothendieck** [SebKrantz/collapse#390]
In the code below I would have expected the output column `v` to be of `Date` class:

```
library(collapse)
packageVersion("collapse")
## [1] ‘1.9.3’

date1 <- function(x) as.Date(x[1], origin = "1970-01-01")
DF <- data.frame(v = 1:6, g = c(11, 11, 11, 12, 12, 12))
collap(DF, ~ g, custom = list(date1 = "v"))
##   v  g
## 1 1 11
## 2 4 12
```

**Comment by SebKrantz** [comment]
Thanks, but *collapse* seeks to preserve the attributes of your input data, calling `copyMostAttrib(agg_v, orig_v)` before finishing (actually the internal version of `copyMostAttrib` is smarter and only does this if `agg_v` and `orig_v` are of the same data type and `orig_v` is not a time series). In any case, you also don't get this behavior in base R, e.g. `unlist(split(wlddev$date, wlddev$iso3c))` is not a date variable.  So I'm afraid there is little I can do here. You need to either coerce to date before or after the aggregation.

**Comment by ggrothendieck** [comment]
In this case the input is Date class and the output of the `f` function is also Date class but it still strips the class so it seems that it does not preserve the class attribute.

```
library(collapse)
library(dplyr)
packageVersion("collapse")
## [1] ‘1.9.3’
 
f <- function(ix) DF$d[unclass(ix)][1]
DF <- data.frame(d = as.Date("2000-01-01") + 0:5, g = c(1, 1, 1, 2, 2, 2))
DF %>%
   fmutate(d = .Date(1:nrow(DF))) %>%
   collap(~ g, custom = list(f = "d"))
##           d g
## 1 10957 1
## 2 10960 2

**Comment by SebKrantz** [comment]
Nope, it's nothing about the date, it it seems `str(unclass(.Date(1:10)))` creates an underlying object of class integer, which is not a valid date `str(unclass(as.Date("1970-01-01")))` is double. There is a check in the internal version of `copyMostAttrib()` to not copy attributes when the original column is integer typed, mainly due to issues with factors. But I agree this could be made smarter, also in light of *data.table*'s 'IDate' class. But with proper dates e.g. 

```
f <- function(x) x[1]
DF <- data.frame(d = as.Date("2000-01-01") + 0:5, g = c(1, 1, 1, 2, 2, 2))
collap(DF, ~ g, custom = list(f = "d"))
```
gives what you want.

**Comment by ggrothendieck** [comment]
Suggest that this be documented in `?collap`  sufficiently so that one can predict what output one will get for a given function.

**Comment by SebKrantz** [comment]
So in your particular cas I don't think anything requires fixing, it's just a matter of thinking how things should behave. *collapse* strives to preserve attributes in all circumstances except when it is likely to break something. The patterns described here are also not unique to `collap()` but applied throughout the package. But I agree they could be better still, particularly for specialized classes like 'IDate', and I could make a vignette describing in general how *collapse* deals with attributes and manages to be class agnostic. So thanks for alerting me here.

**Comment by SebKrantz** [comment]
So just to get back to this, I've now added an exception for data.table 'IDate' and 'ITime'. So the C function deciding to keep attributes with base R functions applied over groups now looks like this: 

```c
SEXP my_copyMostAttrib(SEXP x, SEXP y) {
  if(TYPEOF(x) == TYPEOF(y) && (OBJECT(x) == OBJECT(y) || TYPEOF(x) != INTSXP || inherits(y, "IDate") || inherits(y, "ITime"))) 
    copyMostAttrib(y, x);
  return x;
 }
```
Where `x` is the result of a computation carried out on R e.g. 

```r
x = unlist(lapply(gsplit(y, g), FUN, ...), use.names = FALSE)

```
Literally this is what happens under the hood if you don't use fast statistical functions (which have internal grouped logic). So the challenge, as you see, is that we only have `x` and `y`, and based on the properties of `x` and `y` we need to decide whether to copy attributes from `y` to `x` or not:
```r
x = .Call(my_copyMostAttrib, x, y)
```
The condition inside `my_copyMostAttrib` reads: if `x` and `y` have the same data type and either the same class (checked by `OBJECT()` in C), or if `x` is not integer (as FUN could be something like `length()` or `sum(!is.na(x))` etc.) or, now, if `y` was either IDate or Ttime.  As mentioned above, regular dates are double, and attributes should thus be copied if `FUN` keeps the data type double. Factors are also handled by this expression, because `unlist()` actually has an internal method to combine a list of factors to a single factor, so `OBJECT(x) == OBJECT(y)` is `TRUE` in that case. Anyway, this is probably too detailed for a vignette, but I wanted to give you an understanding of what I do and why. In a nutshell: this is the best check I could come up with so far, given the constraints of the problem i.e. only knowing `x` and `y`.

**Comment by ggrothendieck** [comment]
OK. Thanks.
