### ISSUE TITLE
qG object maintains number of groups after subset

### ISSUE THREAD

**Issue by NicChr** [SebKrantz/collapse#391]
Hello, 
I noticed some strange results with qGs after subsetting, please see the example below where I create a vector of integers, 1 through to 10, coerce to "qG" class, and filter on the first group. The resulting "qG" object maintains an attribute of 10 groups. 

``` r
g1 <- 1:10 # Groups
dt1 <- data.table::data.table(g1)

dt1[, ("g2") := collapse::qG(g1)] # Make qG
g2 <- dt1[get("g1") <= 1, ]$g2 # Filter on group 1

g2 # Has 10 groups
#> [1] 1
#> attr(,"N.groups")
#> [1] 10
#> attr(,"class")
#> [1] "qG"
collapse::group(g2) # Has 1 group
#> [1] 1
#> attr(,"N.groups")
#> [1] 1
#> attr(,"class")
#> [1] "qG"          "na.included"
collapse::GRPN(g2, expand = FALSE)
#>  [1] 1 0 0 0 0 0 0 0 0 0
collapse::GRPN(g2) # Expanded version is smaller than non expanded..
#> [1] 1
```

<sup>Created on 2023-03-26 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

As the documentation specifies this is more for programmers, this isn't a major issue as such, but I think it might be helpful to document this behaviour more explicitly if it is intended.

**Comment by SebKrantz** [comment]
Thanks. Yes, there is no method `[.qG`, so the default method applies, which keeps attributes. 'qG' is meant to be a factor-light class, and subsetting a factor also maintains all the factor levels, so I don't think this behavior is appropriate to the intent behind the class. I don't intend to write further documentation here because I would be documenting base R. The simply are no subsetting methods for 'qG' objects which automatically means that base R applies.
