### ISSUE TITLE
Possible bug in flag?

### ISSUE THREAD

**Issue by skranz** [SebKrantz/collapse#404]
I am just testing out collapse and it seems like a great package. (If there would be a contest between package authors whose name matches the glob "Sebastian Kran*z", you would definitely win!)

I am just a bit confused with the following behavior of the flag function:
```r
  data <- data.frame(time = c(1, 3:5),value = rnorm(4))
  data$lag_value = collapse::flag(data$value, t=data$time)
  data

```
Yields:
```
  time     value lag_value
1    1 -1.386361        NA
2    3  1.881305 -1.386361
3    4 -1.272152  1.881305
4    5  1.263261 -1.272152
```

I thought that lag_value in the second should also be NA since time=2 is missing. If instead time=3 is missing, it works as expected:
```r
  data <- data.frame(time = c(1:2, 4:5),value = rnorm(4))
  data$lag_value = collapse::flag(data$value, t=data$time)
  data
```
```
  time      value  lag_value
1    1 -0.8454623         NA
2    2  0.2433548 -0.8454623
3    4  0.1146327         NA
4    5  0.6810534  0.1146327
```
Is the behavior for the first example a bug, or have I overlooked something?

I am using version 1.65 of collapse (just downloaded it from CRAN).

**Comment by SebKrantz** [comment]
Thanks! I would recommend using collapse 1.8 and upwards (why not use the latest version?), v1.8.0 has had a [change in the parsing of the time input](https://sebkrantz.github.io/collapse/news/index.html#changes-to-functionality-1-8-0). To cut it short, 1.8.0 and upwards give what you expect. The current parsing is also described in the details of `flag()`:

"Note that the t argument is processed as follows: If is.factor(t) || (is.numeric(t) && !is.object(t)) (i.e. t is a factor or plain numeric vector), it is assumed to represent unit timesteps (e.g. a 'year' variable in a typical dataset), and thus coerced to integer using as.integer(t) and directly passed to C++ without further checks or transformations at the R-level. Otherwise, if is.object(t) && is.numeric(unclass(t)) (i.e. t is a numeric time object, most likely 'Date' or 'POSIXct'), this object is passed through [timeid](https://sebkrantz.github.io/collapse/reference/timeid.html) before going to C++. Else (e.g. t is character), it is passed through [qG](https://sebkrantz.github.io/collapse/reference/qF.html) which performs ordered grouping. If t is a list of multiple variables, it is passed through [finteraction](https://sebkrantz.github.io/collapse/reference/qF.html). You can customize this behavior by calling any of these functions (including unclass/as.integer) on your time variable beforehand."

**Comment by skranz** [comment]
Great, thanks! Interestingly, the default repository from RStudio hosted the 1.6.5 version, i.e. I got:

```
> install.packages("collapse")
Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)
trying URL 'https://packagemanager.rstudio.com/cran/__linux__/focal/2021-08-09/src/contrib/collapse_1.6.5.tar.gz'
Content type 'binary/octet-stream' length 10681935 bytes (10.2 MB)
==================================================
downloaded 10.2 MB

* installing *binary* package ‘collapse’ ...
* DONE (collapse)
```
So this was not the current CRAN version. Probably because I still have R version 4.1 and RStudio did not update the Linux binaries. But using

```r
install.packages('collapse', repos='http://cran.us.r-project.org')
```
I got the newest version (1.94) and the example runs without problems!

**Comment by SebKrantz** [comment]
Ok, thanks, this is interesting to know. They also still have the collapse 1.6.1 cheatsheet on their website (from July 2021), so I guess some things have just been discontinued over there.
