### ISSUE TITLE
collapse installation fails on RHEL due to fmean.c

### ISSUE THREAD

**Issue by nmoret** [SebKrantz/collapse#417]
Trying to install collapse with "install.packages("collapse")" on RHEL 7.9, but get the following error:
<img width="882" alt="image" src="https://user-images.githubusercontent.com/7645695/235734888-f9398d1d-345b-4d82-b870-344637ab3ef6.png">

Also tried to download the tar file and use R CMD INSTALL, but got same error. Tried installing both version 1.9.5 and version 1.9.4 --> no difference.

session info:
R version 4.2.2 (2022-10-31)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux Server 7.9 (Maipo)

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblasp-r0.3.3.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
[1] compiler_4.2.2

**Comment by SebKrantz** [comment]
Thanks, this is because `#prama omp parallel for simd` is a modern OpenMP instruction set combining multithreading with SIMD vectorizatrion. Can you try updating OpenMP?

**Comment by SebKrantz** [comment]
Any news here? Otherwise I'll close the issue. My own exterimentation is that it also depends on the compiler version, so ideally both OpenMP and compiler should have been released within the last 2 years.

**Comment by grantmcdermott** [comment]
FWIW, I have to run a CentOS 7 (ugh) on a work server, which I believe is the same architecture as RHEL 7. Setting the  repo location to the appropriate [Posit Package Manager](https://packagemanager.posit.co/client/#/repos/2/overview) endpoint (i.e., fetch the precompiled binaries for your distro) should resolve any compilation headaches.

```r
install.packages("collapse", repos = "https://packagemanager.posit.co/cran/__linux__/centos7/latest")
```

If the above works for you, then you might think about setting PPM as your default repo location rather than one of the regular CRAN mirrors. Add the following to your `~/.Rprofile` file (created this file first if you don't have it)

```
option(repos = c("PPM" = "https://packagemanager.posit.co/cran/__linux__/centos7/latest"))
```

**Comment by SebKrantz** [comment]
Users encountering this problem can use:
```r
remotes::install_github("SebKrantz/collapse", ref = "no_parallel_simd")
```
to install a version of *collapse* that uses normal multithreading without SIMD acceleration.
