### ISSUE TITLE
Question about collap() multithreaded and forked processing

### ISSUE THREAD

**Issue by ummel** [SebKrantz/collapse#421]
The speed of _collapse_ .FAST_STAT_FUN's is really impressive. For large-data applications, the option to use multithreading (nthreads > 1) for `fsum()`, `fmean()`, `fmedian()`, `fmode()`, and `fndistinct()` is extremely useful.

My question is about how `collap()` handles the use case where 'custom' consists of both multithreading-enabled and "other" functions.

Case 1: Serial processing all the way. fsd() and fmean() are called directly.

`collap(wlddev, ~country, custom = list(fsd = 9:13, fmean = 9:13))`

Case 2: This uses multithreading across columns for fmean() but not for fsd(); correctly issues a warning about 'nthreads' not being applicable to fsd(). 

`collap(wlddev, ~country, custom = list(fsd = 9:13, fmean = 9:13), nthreads = 2)`
      
Case 3: Is this internally equivalent to Case 1? Or is forking employed across columns using fsd() and fmean() with vector inputs?

`collap(wlddev, ~country, custom = list(fsd = 9:13, fmean = 9:13), parallel = TRUE, mc.cores = 2)`

Case 4: This computes, even though the arguments imply a "mixing" of multithreading and forking. No warning about 'nthreads' not applicable to fsd(). But what is actually happening internally?

`collap(wlddev, ~country, custom = list(fsd = 9:13, fmean = 9:13), nthreads = 2, parallel = TRUE, mc.cores = 2)`

Case 5: Add a custom function. This unexpectedly fails because 'nthreads' is passed internally to `slowmean()`. That seems like undesirable behavior. I would expect this to behave like Case 2. I assume `slowmean()` is passed to `BY()` internally.
```
slowmean <- function(x) mean(x, na.rm = TRUE)
collap(wlddev, ~country, custom = list(fsd = 9:13, fmean = 9:13, slowmean = 9:13), nthreads = 2)
```
Case 6: Not surprisingly, this fails. But _ideally_ `collap()` would allow this. Since multithreading is always preferable to forking, my expectation in this case is to internally call `fmean(..., nthreads = 2)`; `BY(..., FUN = slowmean, parallel = TRUE, mc.cores = 2)`; and `fsd()` is computed in whatever way it is in Case 4.

`collap(wlddev, ~country, custom = list(fsd = 9:13, fmean = 9:13, slowmean = 9:13), nthreads = 2, parallel = TRUE, mc.cores = 2)`

**Comment by SebKrantz** [comment]
So multithreading is independent of forking parallelism, implemented by calling `parallel::mclapply(..., mc.cores = mc.cores)` instead of `lapply(...)` to iterate across columns. The internal code looks like this

```r
applyfuns_internal <- function(data, by, FUN, fFUN, parallel, cores, ...) {
  oldClass(data) <- "data.frame" # Needed for correct method dispatch for fast functions...
  if(length(FUN) > 1L) {
    if(parallel) return(lapply(seq_along(FUN), function(i)
            if(fFUN[i]) mclapply(data, FUN[[i]], g = by, ..., use.g.names = FALSE, mc.cores = cores) else
              BY.data.frame(data, by, FUN[[i]], ..., use.g.names = FALSE, reorder = FALSE, return = "data.frame", parallel = parallel, mc.cores = cores))) # mclapply(data, copysplaplfun, by, FUN[[i]], ..., mc.cores = cores)

      return(lapply(seq_along(FUN), function(i)
              if(fFUN[i]) FUN[[i]](data, g = by, ..., use.g.names = FALSE) else
                   BY.data.frame(data, by, FUN[[i]], ..., use.g.names = FALSE, reorder = FALSE, return = "data.frame"))) # lapply(data, copysplaplfun, by, FUN[[i]], ...)
  }
  if(is.list(FUN)) FUN <- FUN[[1L]]

  if(parallel) if(fFUN) return(list(mclapply(data, FUN, g = by, ..., use.g.names = FALSE, mc.cores = cores))) else
      return(list(BY.data.frame(data, by, FUN, ..., use.g.names = FALSE, reorder = FALSE, return = "data.frame", parallel = parallel, mc.cores = cores))) # return(list(mclapply(data, copysplaplfun, by, FUN, ..., mc.cores = cores)))

  if(fFUN) return(list(FUN(data, g = by, ..., use.g.names = FALSE)))
  return(list(BY.data.frame(data, by, FUN, ..., use.g.names = FALSE, reorder = FALSE, return = "data.frame"))) # return(list(lapply(data, copysplaplfun, by, FUN, ...)))
}
```
I would presume that if `parallel = TRUE`, other arguments are somehow swallowed in `mclapply()`, which is why you don't get the unused argument warning. If unused arguments are passed to Fast Statistical Functions, what happens is regulated by `options("collapse_unused_arg_action")`, see `help("collapse-options")`. The default is "warning" which issues a warning. I don't know of a very sensible way around this. In general, `collap()` is convenient but somewhat limited. If you want to evaluate each function with it's own set of arguments, I recommend to use `fsummarise()`, where you can combine tagged expressions and `across()` statements at your convenience.

**Comment by ummel** [comment]
OK, so it sounds like there is not an easy/straightforward way for `collap()` to process different `FUN` using different parallelism techniques. And that makes sense about `parallel = TRUE` "swallowing" arguments.

Somewhat related (can move into new issue if you like) is that `...` arguments in `collap()` don't seem to always pass to `FUN`. In my earlier example, `nthreads` is passed, and I would expect `n` for `fnth()` to be passed in the following example. But it isn't.

These should give different results (default median vs. 90th percentile):

`head(collap(wlddev[c(1, 12)], by = ~country, FUN = fnth))`
         country       ODA
1    Afghanistan 261535004
2        Albania 338790009
3        Algeria 381869995
4 American Samoa        NA
5        Andorra        NA
6         Angola 238975006

`head(collap(wlddev[c(1, 12)], by = ~country, FUN = fnth, n = 0.9))`
         country       ODA
1    Afghanistan 261535004
2        Albania 338790009
3        Algeria 381869995
4 American Samoa        NA
5        Andorra        NA
6         Angola 238975006

**Comment by SebKrantz** [comment]
Thanks, this is indeed an interesting one. The issue is that `collap()` has an argument `na.last` and, unfortunately, R matches function arguments partially, so `n` is matched to `na.last` see https://stackoverflow.com/questions/15264994/prevent-partial-argument-matching. The solution I can offer, and I'm pushing it out right now, is to place the `...` argument after `custom`, so that `n` is not matched and passed to `...`.
