### ISSUE TITLE
keep.ids argument in collapse::L() seems not effective on data.table

### ISSUE THREAD

**Issue by Sage0614** [SebKrantz/collapse#425]
I am using collapse 1.9.5 (CRAN version) 
the following code seems not to work as it is intended with data.table:

`
test_data <- expand.grid(id = 1:10, idx = 1:10) %>% setDT()

test_data[, value := 1:100]

grp <- GRP(test_data, by = "id")

L(test_data, cols = "value", n = 1:3, by = grp, keep.ids = TRUE, stub = TRUE)
`

it gives me result like:

    L1.value L2.value L3.value
        <int>    <int>    <int>
  1:       NA       NA       NA
  2:       NA       NA       NA
  3:       NA       NA       NA
  4:       NA       NA       NA
  5:       NA       NA       NA
  6:       NA       NA       NA
  7:       NA       NA       NA
  8:       NA       NA       NA
  9:       NA       NA       NA
 10:       NA       NA       NA
 11:       10       NA       NA
 12:       11       NA       NA
 13:       12       NA       NA
 14:       13       NA       NA
 15:       14       NA       NA
 16:       15       NA       NA
 17:       16       NA       NA
 18:       17       NA       NA
 19:       18       NA       NA
 20:       19       NA       NA
 21:       20       19       NA
 22:       21       20       NA
 23:       22       21       NA
 24:       23       22       NA

where the original ids are dropped but not kept.

**Comment by SebKrantz** [comment]
Hi, thanks, but this is intentional and has nothing to do with the object being a data.table. `keep` arguments only work if the variables are indicated using a formula e.g. `L(test_data, 1:3, value ~ idx)`. The reason is that the full-length grouping columns are not contained in the grouping object. Whenever you are passing something "external" to your data frame to `by`, `t` or `w`, the `keep` arguments don't work, because it is unclear what is to be kept (also considering that you could also pass an atomic vector or (unnamed) list to `by`).  

Another alternative to formulas you have here is the `fgroup_by()` syntax, but also here you need to make sure to select the id column: `test_data |> fgroup_by(idx) |> fselect(idx, value) |> L(1:3)`. In general the formula syntax here is more efficient, because it does less: `GRP()` and `fgroup_by()` perform a full sorted grouping, whereas the formula processing  results in a single call to `group(test_data$idx)`, which performs fast unsorted grouping - all that is required for this operation. 

Of course, if you need the 'GRP' object for other purposes, you have additional programming possibilities, for example
```r
add_vars(L(test_data, cols = "value", n = 1:3, by = grp), 
                 get_vars(test_data, grp$group.vars), pos = "front")
```
A final think I want to make you aware here is this: the documentation for `flag` states that if you do not supply a time variable (`t`), then all values in a group need to be consecutive: `idx` satisfies that requirement, but `id` does not. It still works here because all values are ordered, but that is not always the case. So `L(test_data, 1:3, value ~ idx)` is fine, but `L(test_data, 1:3, value ~ id)` should not be used! To be safe, you can use either of `L(test_data, 1:3, value ~ idx, ~id)` or `L(test_data, 1:3, value ~ id, ~idx)`

**Comment by Sage0614** [comment]
understand, maybe worth some more detailed documentation on the behavior of 'keep.ids' argument? Current document may confuse people that this works with both way to pass 'by' argument but it isn't.
