### ISSUE TITLE
Syntax request: Consistency of old/new argument order across functions

### ISSUE THREAD

**Issue by D3SL** [SebKrantz/collapse#444]
Currently some functions such as `*rename()` follow `old=new` while others such as `*select()` follow `new=old`. It would be very nice if all functions standardized on one idiom, currently muscle memory gets me a lot when I want to rename without using select to do it .

**Comment by SebKrantz** [comment]
Thanks, this is a choice I have made back then and it is difficult to change it without breaking people's code. However, the choice makes some sense, because there is also `relabel()` for which the reverse way looks horrible e.g. `relabel(mtcars, "Number of Cylinders" = cyl)` is rather strange, `relabel(mtcars, cyl = "Number of Cylinders")` makes much more sense. So at least `*rename()` and `*relabel` are consistent like this. I also note that `*rename()` is also consistent with pandas's rename function. 

So the only thing I can offer is adding something like a `.rev` argument to `*rename` so you can `*rename(mpg, new_name = cyl, .rev = TRUE)`. Given that your problem was memorizing the syntax, I'm not sure this is worthwhile though, as you might as well memorize the syntax instead of adding `.rev = TRUE` to every `*rename()` call.

**Comment by D3SL** [comment]
That's interesting, I wasn't aware of any functions following the `old=new` idiom. As far as I know the entire tidyverse (including `rename`) follows `new=old` as does {data.table}'s `:=` and `.()` operators.

I think it comes down to whether you're looking at this as an assignment or as function arguments.

**Comment by SebKrantz** [comment]
I've managed to implement both conventions in an unambiguous way. The default continues to `m <- match(names(args), names(data))`, but if and only if `allNA(m)` it will instead `match(as.character(args), names(data))` and do things the other way around (`args = substitute(c(...))[-1L]`). Will be released with v2.0.0 in 1-2 months.
