### ISSUE TITLE
Suggestion: break stats/non-table functions into a separate package

### ISSUE THREAD

**Issue by orgadish** [SebKrantz/collapse#481]
@SebKrantz I know this is a big ask, so I totally understand if you don't have time to maintain these separately, or you don't think this is worth the effort.

I am using `collapse::funique`, `collapse::whichv` in my package [deduped](https://github.com/orgadish/deduped) to speed up functions that run on vectors with duplication. `collapse` is a rather big dependency for only those two functions. I think the entire `collapse` is great for end-user usage (e.g. with `dplyr` or other data frame pipelines as noted in the examples). I also think the `collapse` package serves as a good great back end tool for improved performance of other packages. If these types of functions were split out from the main package, I think it would significantly increase the appeal for other developers to use this in their packages. 

Again, totally understand if you don't think this is worth the effort. I was happy to include the entire `collapse` package as a dependency in `deduped` because of the performance boost.

**Comment by SebKrantz** [comment]
Thanks, I would like to understand what exactly you mean by "size"? 

In my anaylsis: the source package is 1.4Mb, which is not very large. The size of the precompiled version of the package depends on the system, but may be 4-10Mb. It is a bit larger than *data.table* due to the use of *Rcpp* (which has large header files). The namespace is comparatively large of course, but when using *collapse* as a dependency you don't import the full namespace but only the functions you are using. Otherwise, dependency wise *collapse* is very lightweight (only depends on *Rcpp* which is preinstalled and basically everyone has it). Another consideration is of course the popularity of *collapse* itself, which I expect to be increasing (at least the demonstrably sizeable performance increases in basic everyday operations like table joins should prompt higher uptake if information frictions in the community can be overcome)...

**Comment by orgadish** [comment]
I see 14 MB (see below), but maybe something is weird on my end. I do agree with your other points -- the very light extra dependency makes a big difference.


``` r
packageVersion("collapse")
#> [1] '2.0.3'

system.file("DESCRIPTION", package = "collapse") |> 
  dirname() |> 
  fs::dir_info(recurse=TRUE, all = TRUE) |> 
  getElement("size") |> 
  sum()
#> 13.9M
```

<sup>Created on 2023-10-24 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by SebKrantz** [comment]
Ok, thanks. I'm not sure though if the size of the directory = the size of the precompiled file that you download. But could be that it is 14Mb for your system. As mentioned, without removing Rcpp (which won't happen very soon), this cannot be reduced. The proposal of outsourcing some functions is also infeasible, because most of these functions are also used to speed up operations internally (collapse is a pretty integrated piece of software). So I will close this issue for now, but take note that the installed size may be large on some systems.
