### ISSUE TITLE
join function support 'many-to-many' relationship ? 

### ISSUE THREAD

**Issue by tenFnAN** [SebKrantz/collapse#487]
I would ask that is possibility to make similar tables joins like with the use of dplyr ? I attached code to reproduce example 

```r
df1 = data.frame('DATE_yw1' = c('2019_38', '2019_39', '2019_39'), 'DATE_yw2' = c('2019_37', '2019_37', '2019_38'))
df2 = data.frame('DATE_yw2' = c('2019_37', '2019_37', '2019_38', '2019_38', '2019_38', '2019_38', '2019_38'), 'stat' = runif(7))

df1 %>%   
      dplyr::inner_join(df2, by = 'DATE_yw2', relationship = "many-to-many" ) %>% 
      collapse::roworderv(c('DATE_yw1', 'DATE_yw2'))
    
df1 %>%   
      collapse::join(df2,  on = 'DATE_yw2',how = 'inner', validate = 'm:m' ) %>% 
      collapse::roworderv(c('DATE_yw1', 'DATE_yw2'))
```

Above dplyr solution is what I expect

**Comment by tenFnAN** [comment]
Thank you for the answer, I just wanted to make sure that I understood the join function correctly in the context I mentioned, now everything is clear to me

**Comment by zander-prinsloo** [comment]
Hi, really enjoying the collapse package, so thank you! 

I also have a request/comment on the many-to-many join. There are a number of cases where one may want many-to-many joins rather than just taking the first match or, on the other extreme, taking the cartesian product. The `merge.data.table` function allows both many-to-many joins and the cartesian product. Given the great performance of `collapse`, I'd love to be able to do many-to-many joins. 

The example below shows the difference between data.table and collapse in this case. 

Thank you!



``` r
library(data.table)
library(collapse)
#> collapse 2.0.3, see ?`collapse-package` or ?`collapse-documentation`
#> 
#> Attaching package: 'collapse'
#> The following object is masked from 'package:stats':
#> 
#>     D

set.seed(1)
dt1 <- data.table(
  a = sample(1:5, 10, replace = T), 
  b = sample(1:5, 10, replace = T), 
  d = 1:5
)
dt2 <- data.table(
  a = sample(1:5, 10, replace = T), 
  b = sample(1:5, 10, replace = T), 
  c = 1:5
)
result_datatable <- merge.data.table(
  x = dt1, 
  y = dt2, 
  by = c("a"), 
  all = T, 
  cart = F, 
  sort = T
)
result_collapse <- collapse::join(
  x = dt1, 
  y = dt2, 
  how = "full", 
  sort = T, 
  on = "a", 
  suffix = c(".x", ".y")
)
#> full join: dt1[a] 10/10 (100%) <m:m> dt2[a] 5/10 (50%)
#> duplicate columns: b => renamed using suffix '.x' for x and '.y' for y

result_datatable[a==2]
#>    a b.x d b.y c
#> 1: 2   2 4   4 2
#> 2: 2   2 4   4 3
#> 3: 2   2 4   1 4
#> 4: 2   2 4   2 5
#> 5: 2   5 2   4 2
#> 6: 2   5 2   4 3
#> 7: 2   5 2   1 4
#> 8: 2   5 2   2 5
result_collapse[a==2]
#>    a b.x  d b.y c
#> 1: 2   2  4   4 2
#> 2: 2   5  2   4 2
#> 3: 2  NA NA   4 3
#> 4: 2  NA NA   1 4
#> 5: 2  NA NA   2 5
```

<sup>Created on 2023-11-16 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by SebKrantz** [comment]
Thanks, yeah I could add a `relationship` argument to do this at some point. The `validate` argument, as explained, is only for checking purposes. But also as stated: I'm doing data analysis for quite some years now and I never required a cartesian-type join. Fundamentally such a join indicates underidentified data, and that needs to be dealt with. The usual way of dealing with that is aggregating the joined table in some way, but this can usually also be done in a more memory efficient way by aggregating ex-ante. The only other use I see is generating "value grids" for statistical procedures, but I think there are other solutions such as `expand.grid()` to do that. In any case, implementing this will require some effort on my side, and I would like to be convinced that it is necessary.

**Comment by randrescastaneda** [comment]
Hi @SebKrantz,

As a seasoned Stata user for over 15 years, I wholeheartedly agree with your observation that `m:m` joins are rarely encountered in practice. In fact, I can only recall one instance where I had to use one, and as you mentioned, the data could have been aggregated instead. However, I am wondering whether this scarcity of `m:m` merges among economists is likely due to their intensive use of Stata, which highly discourages their use, rather than to a lack of usefulness in the real world. Nonetheless, Stata does provide `m:m` joins, albeit with the appropriate caveats.

Since `collapse` is widely used beyond the realm of economics, users naturally expect `m:m` joins to function similarly to other join functions in R, such as those found in base R, dplyr, and data.table. While I cannot articulate a compelling argument for including proper `m:m` support in `collapse`, I believe it would be beneficial to accommodate this expectation among R users.

Given the substantial effort required to implement `m:m` joins, I propose displaying a clear warning message in the console whenever `m:m` joins are requested. This would inform users of the limitations of `m:m` joins in `collapse` and prevent them from assuming a bug exists.


Best,

**Comment by SebKrantz** [comment]
I have now added an argument `multiple = FALSE` to the `join` function, available in the master branch. Setting `multiple = TRUE` performs a multiple matching join. Feel welcome to test this, it should produce what you are expecting.
