### ISSUE TITLE
setv for new values

### ISSUE THREAD

**Issue by tony-aw** [SebKrantz/collapse#491]
Hi,

in base R, one can assign new values to vectors, lists, data.frames, etc. like so:
`x <- 1:10 # just an example`
`x[[11]] <- 20`
But I cannot do this by reference with `setv()` (gives an error). Is there some other function in collapse I don't know about that does this? If not, can this be implemented? I know the `data.table::set()` function can insert new values (columns) to data.tables, so it would be nice if collapse can do the same for vectors and lists.
Kind regards,

Tony.

**Comment by SebKrantz** [comment]
Hi, unfortunately this is not possible by reference. The only reason data.table is able to do this by reference is because data.table's themselves are implemented as overallocated lists i.e. the data.table actually has 1024 additional (empty) columns which you don't see (by virtue of soeme C-level tricks). So when you add a column by reference using := or set in data.table, it just fills and makes visible a column that is already there. But the rest of R does not work like that, to extend vectors/lists in R a larger vector/list needs to be created and filled with all the elements of the preveeding one including the elements you add. This cannot be done by reference.
