### ISSUE TITLE
FIFO

### ISSUE THREAD

**Issue by Steviey** [SebKrantz/collapse#512]
Could it be, collapse can cause accumulating FIFO connections- and how to get rid of them? I 'm working with extensive data set-windows.

![image](https://github.com/SebKrantz/collapse/assets/3146082/21222dd5-2375-4e5d-92c2-d6d0f1863780) ... Too many open files

**Comment by SebKrantz** [comment]
Hi, thanks, but I have no idea what FIFO is, and I'm not going to study it unless there is clear evidence that *collapse* is doing something harmful. Please submit a reproducible example and explain what is going on and why it needs to be changed. *collapse* passes rigorous compiled code checks on CRAN, so I don't think memory leakage is an issue.

**Comment by Steviey** [comment]
Well, I have an extensive script mainly developed with collapse. Unfortunately it runs 10+ hours and I can't isolate or simulate parts of it, because the only glimpse I have is, that there are after 2 hours+ to many file handles open. The script calculates ML-features over runner windows- meaning it does the same calculations over and over again in intervals of several minutes. The error message "Too many open files" arises when ever something tries to save something- but it needs 2 hours+ to happen. I read somewhere about FIFO in context of C-coding, but nothing specific to the issue. FIFO should be connections which do not close automatically. Do you have any ideas on my issue?

**Comment by SebKrantz** [comment]
Thanks! This is helpful, but I‘d need to know the exact function call that is causing problems. The segfault us a clear indication of some memory error somewhere. Which function is causing it?

**Comment by Steviey** [comment]
Currently I have no specific function call- even using lobstr-tree.
The final crash can happen whenever something tries to save something, after we have a bunch of open file handles- meaning everywhere. For example after sampling the new features/columns and save them via saveRDS. But even lobstr (getting line-info for debug) won't work properly after that, since it tries to save something too ;-). So the actual problem is the accumulation of file handles- for what we have no line number no function indication yet. Meanwhile I try to get some information about the contents of the FIFO pipes on directory level...

`get sender and client of pipe id:
        lsof -n -P | grep 1359259

        print command of sender pid (result=triggered R shell script):
        ps -p 255386 -o cmd

        print client (result=R, useless):
        ps -p 255488 

        print content of a relevant pipe (failed):
        cat /proc/255386/fd/999

        ...try to solve with ChatGPT...`

**Comment by SebKrantz** [comment]
Ok, just a question: are you using data.table's in this code? and are use using indexed series or frames from collapse?

**Comment by Steviey** [comment]
I guess I don't use data.tables directly. But I m not sure. I don't know what indexed series or frames of collapse mean. Mainly I use matrices and tibbles and often the collapse convertations qTBL(), qM(). 

For the second error you mentioned I have a traceback. But it is relatively useless...
since it is a irrecoverable exception...

```
51: dplyr::mutate(., metaData = purrr::map(data, ~doRoll(.)))
				52: setupGrid %>% dplyr::group_by(mapId) %>% tidyr::nest(data = -any_of(c("mapId"))) %>%     dplyr::mutate(metaData = purrr::map(data, ~doRoll(.)))
				
				An irrecoverable exception occurred. R is aborting now ...
				./prepPreds.sh: line 427: 249493 Segmentation fault      Rscript --vanilla --max-ppsize=500000 newTrigger.R ten66Roll $algoMode

```

**Comment by SebKrantz** [comment]
Ok, thanks. I don't know then which part of collapse code would open file handles. data.table's would be a possiility since they need to be shallow copied, and [indexed structures](https://sebkrantz.github.io/collapse/reference/indexing.html) also create external pointers. But the other code is pretty normal. I don't think in your case this has anything to do with these features. So at the moment there is nothing I can do, unless you can narrow down the problem to a specifica function call. There is not a general problem with collapse as a package, but it may be a specific C-function that might access memory in non-existing places (generally causing a segfault).

**Comment by Steviey** [comment]
Ah ok thank you. I will search a little further.

**Comment by D3SL** [comment]
A bit late to the party here but I think I can offer some insight. What you're describing sounds like a very low level issue that has to do with how R hands interacting with the filesystem and other processes. There's a number of ways this could become an issue and without seeing the actual code it's impossible to be specific.

The obvious one is of course reading and writing files. R treats those as [a connection](https://web.mit.edu/~r/current/arch/i386_linux26/lib/R/library/base/html/connections.html) and depending on how you're handling everything you may not actually ever be closing them. This isn't a collapse specific issue but rather R itself, which is why [several other people](https://www.google.com/search?q=%22R%22+%22too+many+open+files%22+site:stackoverflow.com) have had the same problem with everything from `read_csv()` to base functions like `file()` and `download.file()`.

If I'm right you might be able to find the culprit by running your original script while periodically logging `showConnections(all=TRUE)`. 

As an aside if you're running into this issue there's likely a lot of other places you can optimize your code as well: 

- `fread` and `fwrite` are vastly faster than their tidyverse equivalents, and arrow's `.parquet` files are better still. 
- data.tables are faster and more efficient than tibbles, especially when keyed well.
- pipes (particular the base pipe) are pretty fast but with absolutely huge objects the overhead can be non-trivial.
- IF you're doing operations that make deep copies then update-by-reference will be massively faster and use half the memory.

And on a much more advanced level there's multithreading. By nature every call to `map` is a parallelizable operation. The question is whether the objects involved are serializable, whether serialization overhead will outstrip parallelization gains, and if you have enough RAM for each child process. Crew's efficient Mirai backend nearly moots the overhead issue but is a bit more complicated to use than the others.  The use of external R processes may also help with your connection issues since you'll have greater control over the workers and controller.
