### ISSUE TITLE
`whichv` behavior with missing values

### ISSUE THREAD

**Issue by eutwt** [SebKrantz/collapse#518]
I have a package where I use the function below. I use this instead of `which(x != y)` so that if there's an element where`x[i]` is missing but not `y[i]`, `i` is included in the output vector.

``` r
which_not_equal <- function(x, y) {
  which(data.table::fcoalesce(x != y, is.na(x) != is.na(y)))
}
which_not_equal(1, NA)
#> [1] 1
which(1 != NA)
#> integer(0)
```

<sup>Created on 2023-12-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

I recently found that `%!=%` has exactly this behavior and is much faster. So I want to confirm, is the behavior below intentional and something I can rely on, or unintentional "off-label" behavior I shouldn't rely on?

``` r
suppressPackageStartupMessages(library(collapse))

NA %!=% NA
#> integer(0)
1 %!=% NA
#> [1] 1
NA %!=% 1
#> [1] 1

NA_character_ %!=% NA_character_
#> integer(0)
"a" %!=% NA_character_
#> [1] 1
NA_character_ %!=% "a"
#> [1] 1
```

<sup>Created on 2023-12-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

By the way, thanks for a great package! Using`ss(check = FALSE)` has made the main function in my package much faster.

**Comment by eutwt** [comment]
Actually it only behaves like the `which_not_equal()` function above where there is one element (the inconsistency seems like a bug)

``` r
suppressPackageStartupMessages(library(collapse))

x <- c(NA_real_, 1)
x %!=% x
#> [1] 1
x[1] %!=% x[1]
#> integer(0)
```

<sup>Created on 2023-12-27 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

**Comment by SebKrantz** [comment]
Thanks, yeah I had added an exception for double vectors for a single value, but not for vectors. The issue is that with double vectors in C `NA_REAL == NA_REAL` is `FALSE` and `NA_REAL != NA_REAL` is `TRUE`. This is not the case with any other vectors (integer, logical or string). I had created a template code that just compares vector elements using `==` or `!=` without special treatment of doubles, mainly for efficiency reasons. But I see now that this should be consistent, and I have now added the extra conditionals for doubles.
