### ISSUE TITLE
rowbind when element of input is NULL

### ISSUE THREAD

**Issue by tyner** [SebKrantz/collapse#619]
`collapse::rowbind` is advertised as similar to `data.table::rbindlist` however the two do not behave similarly when given this input:

```r
collapse::rowbind(list(NULL, iris))     # returns a list of vectors (lacks a data.frame class)
data.table::rbindlist(list(NULL, iris)) # returns a data.table
```
Of course in the case of the former one can manually class it as a `data.frame`, but it might be nice to do that automatically. Thank you for considering.

I am using version 2.0.15 of `collapse`.

**Comment by SebKrantz** [comment]
Please see the return argument of `rowbind()`. Should explain this behavior.

**Comment by SebKrantz** [comment]
Ok, I see you've already discovered it. So this default is there because you may not be interested in rowbinding just data.tables, but also tibbles,sf data frames, or any other list-based objects. Its thus a very sensible default, and it is not too much tu ask to specify `return = "data.table"` if it needs to be a data.table.

**Comment by tyner** [comment]
That is fair. I was thinking perhaps the default of `return = "as.first"` might want to examine the first non-NULL element, but I take your point that in the current state the behavior is consistent with the documentation.
