### ISSUE TITLE
Discrepancy in Target Sum Calculation for Weighted Quantiles

### ISSUE THREAD

**Issue by Jahnic-kb** [SebKrantz/collapse#659]
**Description:** There appears to be a discrepancy of the provided target sum definition provided in the “Details” and the "Examples" section of the documentation (https://sebkrantz.github.io/collapse/reference/fquantile.html).

**Details:** In the “Details” section, the target sum is calculated using the formula:
`sumwp = (sum(w) - min(w)) * p`

where min(w) is the smallest supplied weight. However, this definition does not match the computed values in the example.

In the example, min(w) seems to be defined differently: `w[o][1L]`
Here, o represents the indices of the ordered data, so w[o] corresponds to the weights ordered from lowest to highest according to the supplied values (x). Thus, w[o][1] gives the weight associated with the smallest value in the data, which may not necessarily be the supplied smallest weight (min(w)).

This discrepancy appears to lead to unexpected and difficult to explain results in the weighted quantile computation. Notably, the example computes the same values as the fquantile function itself. I could not replicated the fquantile results using the definition given in the description.

**Request:** Could someone clarify which definition of min(w) is correct? Is this a mistake in the documentation or the computation itself?

Thank you for your assistance.

**Comment by SebKrantz** [comment]
Thanks! As far as I can see there is a bug in the documentation, and possibly in the algoithm. It should be the minimum weight and not the weight of the first element. That being said, unless the first (smallest) element has a large weight, which is unlikely in most samples, the differences are not going to be big.

**Comment by Jahnic-kb** [comment]
Thank you for your prompt response and clarification. It’s helpful to know that the intended definition should be the minimum weight. While I agree that the issue of the first element having a large weight is generally rare, in our specific case, it appears frequently enough that our customers are noticing unexpected results.

Could you please confirm if there are any plans to address this potential bug in the algorithm? If so, we would greatly appreciate an update on the timeline for a bug fix so we can plan accordingly for our system updates.

Thank you again for your assistance.

**Comment by SebKrantz** [comment]
I've fixes this just now, and am rolling it out on GitHub. You'll be able to have the updated version via R-universe in a bit more than an hour. Note that this is still v2.0.17 (I keep the same version until a CRAN release to avoid the profileration of versions).

**Comment by SebKrantz** [comment]
The fix has now been deployed to R-universe. It's the minimum positive weight btw. zero weight elements are removed as in the R example.

**Comment by SebKrantz** [comment]
And it has made it to CRAN.

**Comment by Jahnic-kb** [comment]
Hello again,
Since we will be communicating with affected users, we tried to understand the mathematical algorithm as outlined in the documentation. We found two points that still lead to questions for which we have difficulties supplying intuitive answers. It would be great if you could provide us with either a single or multiple sources that we could use to understand the two mathematical steps in question for the Type 7 quantile calculation.
1.	In the documentation, you mentioned that the calculation of the target sum resembles that of the unweighted case and provided the corresponding formula `(n - 1) * p`. However, this seems unintuitive when considering the definition of a quantile. My understanding is that the **(x)th** percentile is defined as a point (**P**) within the range of the supplied data for which (**x%**) are below or equal to the value of (**P**). I would, therefore, expect the target to be above or equal to `n * p`, but `(n - 1) * p < n * p`. Furthermore, the Type 7 formula for calculating the target sum according to [Wikipedia](https://en.wikipedia.org/wiki/Quantile#Estimating_quantiles_from_a_sample) is `(n-1) * p + 1`, which would be as expected bigger or equal to `n * p`. This would correspond to `sumwp = (sum(w) - min(w)) * p + min(w)` in the weighted case.
2.	The second point in question is the choice of values to compute the weighted average with. Intuitively, I would expect the formula to be `(1 - hl) * x[o[j]] + hl * x[o[j-1L]]`, using `j-1` instead of `j+1`,  `since x[o[j]] > sumwp`.

Could you please check if these two points are correctly implemented and, if so, provide the mathematical sources you used to base your implementation on? This would greatly help us find the right path forward for communicating the situation to our customers.
Thank you again for your assistance so far and for any help you can provide to clarifying the remaining questions we have.

**Comment by SebKrantz** [comment]
Hi, so these alterations are due to zero indexing in C and efficient implementation (basically I subtract 1 from h). This needs to be done to get the correct element on a zero index scale. You can find the implemntation [here](https://github.com/SebKrantz/collapse/blob/6f2515d4eebb61f0119b42a6fc2816a22f99d355/src/fnth_fmedian_fquantile.c#L58). This is equivalent to R's quantile function for all quantile types and tested with thousands of tests (see [here](https://github.com/SebKrantz/collapse/blob/master/tests/testthat/test-fquantile.R)). The weighted translation replacing `n` with `sumw` and `1` with `min(w)` is indeed heuristic. However, it seems well behaved. 

The only convincing resource on weighted quantiles that I discovered actually a few days ago is [this document](https://htmlpreview.github.io/?https://github.com/mjskay/uncertainty-examples/blob/master/weighted-quantiles.html) by Matthew Kay. It proposes a way to translate the default quantile definitions to the weighted case using normalized weights, i.e., without calculating a minimum weight or making any other decision on the "unit" of weights. He also tests other quantile methods in a nice theoretically consistent way. *collapse* indeed had a bug, but I tested it after the fix and the results are within the reasonable bounds, see [here](https://github.com/mjskay/uncertainty-examples/issues/2). Thus, I might do another update to the algorithm and implement Matthew Kay's method, but for now it appears that my method of translating the thresholds has reasonable properties as well (all quantile methods which give estimates within the bounds). According to this document it is certainly the best estimator currently implemented in R packages.

**Comment by Jahnic-kb** [comment]
Thank you for the detailed explanation and the resources provided!

Your clarification on the zero indexing in C makes sense and I especially appreciated the reference to Matthew Kay’s document on weighted quantiles.

Thanks again for your assistance and for addressing our questions so comprehensively. This will greatly help us in communicating the situation to our customers.

**Comment by SebKrantz** [comment]
Happy to be of further help. I wish, as you, that there would be a clear definition of weighted quantiles, but there aint. What Matthew Kay proposes is good, and what I do is decent. As mentioned, will probably switsh to his method at some point. This would give very minor changes to the current estimates. I'll let you know here when that happens.
