### ISSUE TITLE
[Bug?] `qF()` runs forever

### ISSUE THREAD

**Issue by mayer79** [SebKrantz/collapse#666]
By chance, I was using `qF(c(4L, 1L, NA), sort = FALSE)` in a unit test. And it does not stop calculating!
Other numbers are fine, e.g., `qF(c(3L, 1L, NA), sort = FALSE)`.

**Comment by SebKrantz** [comment]
Thanks, I'll look into it. I also find this. Very strange.

**Comment by SebKrantz** [comment]
Thanks, I fixed it. Rather serious coding bug, the hash function looked like this: 
```c
  while(h[iid]) { // Check if this hash value has been seen before
    if(px[h[iid]-1] == px[i]) { // Get the element of x that produced his value. if x[i] is the same, assign it the same index.
      pans_i[i] = pans_i[h[iid]-1]; 
      goto ibl;
    } // else, we move forward to the next slot, until we find an empty one... 
    if(++id >= nu) id = 0; 
  } 
```
It should have been `if(++iid >= nu) iid = 0;` instead of `if(++id >= nu) id = 0; `. This was a spacial case of the hash function for integers with missing values. `nu` is the length of the vector (3 in this case). Because `4 > 3`, the `if()` statement didn't execute and the loop ran forever. Now fixed and in the master branch. I should write more tests...
