### ISSUE TITLE
fmean with grouping where dataset has non numeric vectors

### ISSUE THREAD

**Issue by srk7774** [SebKrantz/collapse#673]
I request you to provide output instead of throwing error when ```fmean``` applied to a dataset with non-numeric columns with some warning.
``` r
pacman::p_load(collapse)

# no output with some weired message
fmean(iris, iris$Species)
#> Error in as.character.factor(x): malformed factor

#works
fmean(num_vars(iris), iris$Species)
#>            Sepal.Length Sepal.Width Petal.Length Petal.Width
#> setosa            5.006       3.428        1.462       0.246
#> versicolor        5.936       2.770        4.260       1.326
#> virginica         6.588       2.974        5.552       2.026

#works too
BY(iris, iris$Species, fmean)
#>            Sepal.Length Sepal.Width Petal.Length Petal.Width Species
#> setosa            5.006       3.428        1.462       0.246       1
#> versicolor        5.936       2.770        4.260       1.326       2
#> virginica         6.588       2.974        5.552       2.026       3
```

<sup>Created on 2024-12-11 with [reprex v2.1.1](https://reprex.tidyverse.org)</sup>

**Comment by SebKrantz** [comment]
Thanks, but this is correct, because `"Species"` is a factor and `fmean()` returns doubles, i.e. `typeof(fmean(iris$Species, iris$Species))` is "double" whereas the factor is based on "integer" vector. The `BY()` statement does split-apply-combine and in this case removes the "factor" class. In general, numeric operations should not be performed on factors. You can use `unclass()` to turn the factor into an integer vector.

**Comment by srk7774** [comment]
I know this is correct, but providing some output is always good with some warning. I request you to consider this for future version.

**Comment by SebKrantz** [comment]
The error is not coming from `collapse`, but from `print.factor` which detects that this was a malformed factor.
