### ISSUE TITLE
R CRAN check issue

### ISSUE THREAD

**Issue by NicChr** [SebKrantz/collapse#676]
Hi, first of all sorry for opening so many issues! Appreciate any time you have to reviewing this.

Upon uploading a new version of my package timeplyr to CRAN, it was rejected due to this check pointing to lines 769, 770 and 779 in the kit-dup.c file. 

Error message can be found here
https://win-builder.r-project.org/incoming_pretest/timeplyr_0.9.0_20241210_142954/specialChecks/gcc-san/summary.txt

Many thanks!

**Comment by SebKrantz** [comment]
Ahh, that's really too bad. The error comes from expressions of the form: 

```c
  int *pst = INTEGER(st), k = 0;
  memset(pst, 0, sizeof(int) * ng); --pst;
  for(int i = 0; i != n; ++i) {
    if(pst[pres[i]] == 0) {
      pst[pres[i]] = i + 1;
      if(++k == ng) break;
    }
  }
``` 
where `pres` points to an R integer vector starting from 1. The issue is that `--pst` decremets the pointer to the -1th element, which doesn't exist. But this is not a problem because `pres` is 1-indexed, so to target the 0th element in C I need a decremented pointer. Of course I could rewrite the loop as 

```c
  for(int i = 0; i != n; ++i) {
    if(pst[pres[i]-1] == 0) {
      pst[pres[i]-1] = i + 1;
      if(++k == ng) break;
    }
  }
```
but this is more costly than decrementing the pointer once. 

Perhaps can you reply-all to CRAN and explain this.

**Comment by aitap** [comment]
Unfortunately, C makes it undefined behaviour to [use pointer arithmetic to advance a pointer outside the bounds of the original array plus one element past the end of it](https://port70.net/%7Ensz/c/c11/n1570.html#6.5.6p8), and R returns an invalid data pointer for 0-length arrays, which makes almost all operations with it undefined behaviour.

I think that UBSan won't yell at you for decrementing non-0-length data pointers because there's the `SEXPREC` header there and you never dereference `ptr[0]`, but you might have to add a special case for 0-length vectors.
