### ISSUE TITLE
performance questions

### ISSUE THREAD

**Issue by waynelapierre** [SebKrantz/collapse#70]
I haven't tried your collapse yet but I am curious about its performance. I use data.table and Rfast for performance. Is the collapse package faster than data.table + Rfast? In addition, how does the collapse package using multiple threads?

**Comment by SebKrantz** [comment]
I made some notes about that at the bottom of [this](https://sebkrantz.github.io/collapse/) page which should clarify the matter, and the [blog post](https://sebkrantz.github.io/Rblog/2020/08/31/welcome-to-collapse/) offers some benchmarks on trade data (2.6 million obs). These benchmarks are run on a 2 x 2.2 GHZ laptop. 

The short answer is: collapse currently does not use parallel processing at all, it is serially compiled. The speed comes through fast algorithms it uses to perform grouped statistical computations. On my 2 core laptop this is always faster than data.table. If you have great processing power (4 cores +), data.table is probably faster on aggregations using functions like mean or sum etc. collapse will probably still be faster for transformations (`:=` operations because those are vectorized in C++ as well). But it depends a lot on what you are doing, and what operations data.table will optimized in the future. I don't think data.table will ever be faster at scaling / centering data, weighted aggregation or panel-data (lag, difference etc.) computations than collapse.
