### ISSUE TITLE
namespace with custom argument

### ISSUE THREAD

**Issue by harvey131** [SebKrantz/collapse#81]
Is it possible to use the collap 'custom' argument without loading the collapse library?  When specifying the function names of in the 'custom' argument, which are the names of the elements, it is not possible to name the  element _list(collapse::fmean = 9:12, ...)_

```
head(collapse::collap(collapse::wlddev, ~ country + decade, custom = list(fmean = 9:12, fsd = 9:10, fmode = 7:8)))       
Error in get(as.character(FUN), mode = "function", envir = envir) : 
  object 'fmean' of mode 'function' was not found
```

**Comment by SebKrantz** [comment]
Hi, thank you! But I think this is difficult. Internally collap runs a `names(custom) %in% .FAST_STAT_FUN` and then calls `match.fun()` on the names. The thing is that something like `match.fun("collapse::fmean")` does not work if the package is not loaded. I could rewrite my own `match.fun()` of course which additionally always searches the collapse namespace, but that seems to be a big effort for such cases. The easiest solution would be to just load the functions individually beforehand: 

```
fmean <- collapse::fmean; fsd <- collapse::fsd; fmode <- collapse::fmode
collapse::collap(collapse::wlddev, ~ country + decade, custom = list(fmean = 9:12, fsd = 9:10, fmode = 7:8))
rm(fmean, fsd, fmode)
```
Note also that the issue is not unique to the custom argument, you just get the error there. Take for example
```
collapse::collap(collapse::wlddev, ~ country + decade, collapse::fmedian)
```
This executes, but still collapse doesn't recognize that you are calling `fmedian`, so internally you get a call to `collapse::BY(data, groups, collapse::fmedian)`, which performs split-apply combine-computing using a generic function, and is much slower than `fmeadian(data, groups)` which would be called if `fmedian` were loaded:

```
library(microbenchmark)
fmedian <- collapse::fmedian
microbenchmark(A = collapse::collap(collapse::wlddev, ~ country + decade, collapse::fmedian),
               B = collapse::collap(collapse::wlddev, ~ country + decade, fmedian))
# Unit: milliseconds
#  expr      min        lq      mean    median       uq        max neval cld
#     A 65.70197 66.638643 71.637842 68.310733 75.92618 126.633100   100   b
#     B  3.00548  3.085581  3.209214  3.148502  3.28260   4.307185   100  a
```

**Comment by harvey131** [comment]
OK, maybe that could be documented in collap because I was using it as in your last example with collapse::fmedian

**Comment by SebKrantz** [comment]
Hi, the documentation is updated in collapse 1.4.1 (released shortly). Thank you.

**Comment by SebKrantz** [comment]
In collapse 1.5.0 just released, the code `collapse::collap(collapse::wlddev, ~ country + decade, custom = list(fmean = 9:12, fsd = 9:10, fmode = 7:8))` executes, which is indeed due to an alteration of `match.fun()`. Note that `collapse::collap(collapse::wlddev, ~ country + decade, FUN = fmean)` does not work as `fmean` is not found, but you can do `collapse::collap(collapse::wlddev, ~ country + decade, FUN = "fmean")`.
