### ISSUE TITLE
collap weighted aggregation of some columns only.

### ISSUE THREAD

**Issue by cstepper** [SebKrantz/collapse#96]
Hi, 
not sure if this is an issue or if I'm doing something wrong here. 
I want to aggregate a `data.table` applying *sum* to some variables, and *weighted.mean* to another.
If I aggregate only the sum variables, everything works fine. But when I add the weighted.mean variable, the sum variables get messed up! Any idea? 

``` r
library(data.table)
library(collapse)
#> collapse 1.4.2, see ?`collapse-package` or ?`collapse-documentation`
#> Note: stats::D  ->  D.expression, D.call, D.name
#> 
#> Attaching package: 'collapse'
#> The following object is masked from 'package:stats':
#> 
#>     D

dt <- data.table(
  a = rep(1:10, 100), 
  b = rnorm(n = 1000, mean = 100, sd = 20), 
  c = rnorm(n = 1000, mean = 1000, sd = 100), 
  d = rnorm(n = 1000, mean = 10000, sd = 200), 
  e = rnorm(n = 1000, mean = 40, sd = 30), 
  key = "a"
)

# sum only
dt_aggr <- dt[, 
              .(b = sum(b), 
                c = sum(c), 
                d = sum(d)
              ), 
              by = a 
]

dt_collap <- collap(dt, by = ~ a, 
                    custom = list(fsum = c("b", "c", "d")),
                    give.names = FALSE, keep.col.order = FALSE)

all.equal(dt_aggr, dt_collap)
#> [1] TRUE


# use custom function with sum and weighted.mean

dt_aggr <- dt[, 
              .(b = sum(b), 
                c = sum(c), 
                d = sum(d),
                e = weighted.mean(e, b)
              ), 
              by = a 
]

dt_collap <- collap(dt, by = ~ a, 
                    custom = list(
                      fsum = c("b", "c", "d"),
                      fmean = "e"
                      ),
                    w = ~ b, keep.w = FALSE, 
                    give.names = FALSE, keep.col.order = FALSE)

dt_aggr
#>      a         b         c         d        e
#>  1:  1  9985.163 100656.28 1000460.5 43.45476
#>  2:  2 10215.605 101369.08 1001280.4 38.81689
#>  3:  3 10132.684 100015.69  998257.2 45.00704
#>  4:  4 10299.465  99359.17  998097.4 38.94448
#>  5:  5  9905.694  99733.19 1001845.9 37.09333
#>  6:  6  9988.843  98280.45 1002948.9 41.16864
#>  7:  7  9959.367  99793.90  995675.8 37.17596
#>  8:  8  9919.158  99717.87  998518.1 39.40925
#>  9:  9  9893.985  99670.91  999392.1 40.97915
#> 10: 10  9675.062  99277.57  997792.6 44.98985
dt_collap
#>      a         b        c         d        e
#>  1:  1 1034167.1 10040221  99905293 43.45476
#>  2:  2 1079467.2 10379496 102277718 38.81689
#>  3:  3 1070231.1 10112437 101265286 45.00704
#>  4:  4 1104998.8 10192585 102704800 38.94448
#>  5:  5 1019286.8  9875563  99210893 37.09333
#>  6:  6 1036688.8  9809949 100116781 41.16864
#>  7:  7 1021060.7  9926199  99127299 37.17596
#>  8:  8 1018893.5  9894616  99034998 39.40925
#>  9:  9 1017878.8  9847994  98895093 40.97915
#> 10: 10  979306.1  9594276  96542945 44.98985
```

<sup>Created on 2020-11-23 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by SebKrantz** [comment]
Hello, thanks for bringing this up. I have expected someone to bring this up at some point and I will also write a blog post explaining it. To start off, this is not an error. *collapse*, in an attempt to cater to all possible uses such as calculating survey totals, also offers weighted sums and products. weights passed to `w` in `collap` are passed to all functions, so you are calculating an weighted sum and a weighted mean. There are 2 workarounds, actually 3. I will give you all of them. 

(1) Since you do not want to preserve the column order, the easiest solution would be to just use the `fgroup_by` syntax:

```
dt_collap1 <- dt %>% fgroup_by(a) %>% {
       add_vars(fsum(fselect(., b, c, d)),
               fmean(fselect(., e, b), b, keep.group_vars = FALSE, keep.w = FALSE)) 
}

# Using the available function shortcuts you can also write this more compactly
dt %>% gby(a) %>% {av(fsum(slt(., b, c, d)),
        fmean(slt(., e, b), b, keep.group_vars = FALSE, keep.w = FALSE)) }
```
Note also that `add_vars()` also has a `pos` argument to reorder columns if you wish to. 

(2) You can also use `collap`, and if you do not care too much about performance or your data is moderately sized, you can use `sum` from the base package (which will be applied using `collapse::BY` drawing on base R's `lapply(split(x, g), FUN, ...)` syntax):

```
dt_collap2 <- collap(dt, by = ~ a, 
                    custom = list(
                      sum = c("b", "c", "d"),
                      fmean = "e"
                      ),
                    w = ~ b, keep.w = FALSE, na.rm = TRUE,
                    give.names = FALSE, keep.col.order = FALSE)
```
Note the added `na.rm = TRUE` argument here, which is the default for all *collapse* functions but not for base R. 

(3) you can also use `collap` with `fsum`, but but then you need to play a small trick:
```
# Redefining fsum as aa function without weights
fsum <- function(x, g, w, ...) collapse::fsum(x, g, ...)

# Using your code:
dt_collap3 <- collap(dt, by = ~ a, 
                    custom = list(
                      fsum = c("b", "c", "d"),
                      fmean = "e"
                      ),
                    w = ~ b, keep.w = FALSE, 
                    give.names = FALSE, keep.col.order = FALSE)
# removing
rm(fsum)
```
These are all numerically equivalent to the *data.table* example

```
all_obj_equal(dt_aggr, dt_collap1, dt_collap2, dt_collap3)
## [1] TRUE
```

Let me close with a small benchmark:

```
dt_large <- replicate(1000, dt, simplify = FALSE) %>% unlist2d(DT = TRUE) %>% 
                  ftransform(a = unattrib(finteraction(.id, a)), .id = NULL)

fnrow(dt_large)
## [1] 1000000

library(microbenchmark)
options(warn = -1)

# These are function wrappers around the above expressions
microbenchmark(DT(), clp_1(), clp_2(), clp_3(), times = 10)
Unit: milliseconds
##    expr       min        lq      mean    median        uq       max neval cld
##    DT() 139.27657 145.70836 168.74418 153.86847 161.77823 325.16831    10   b
## clp_1()  21.84925  23.36337  24.13507  23.78374  24.88374  27.38675    10  a 
## clp_2() 112.66138 121.96612 143.90288 126.26528 138.04626 294.54090    10   b
## clp_3()  21.10580  23.50929  27.26542  28.60256  31.12944  31.55026    10  a 

options(warn = 1)
```

I'm sorry for the inconvenience in this case, but I don't know how to make a better API that caters to all possible use cases, including people willing to calculate survey totals and use `fsum` outside of `collap`.

**Comment by cstepper** [comment]
Hi @SebKrantz ,
thanks for this very detailed and comprehensive answer. This makes all sense to me now. 
But I didn't get my head around that `fsum` is using the weight `w` as well when reading the `collap` help. 
I think a blog post would be very good here for people to understand how to use the `custum` argument in `collap`.
Great package, will definitely use it in future!
Cheers, Christoph

**Comment by SebKrantz** [comment]
collapse 1.5.0 now provides an efficient workaround: `collap(data, ~ id, custom = list(fsum_uw = ..., fmean = ...), w = ~weight)`. The postfix `_uw` is available for all fast statistical functions, but only available inside `collap()`.
