### ISSUE TITLE
Is there an alternative solution for function case_when in the dplyr?

### ISSUE THREAD

**Issue by NetZissou** [SebKrantz/collapse#98]
Hi Krantz! I feel like this package has so much potential, and I plan to get familiar with the grammar during the winter. 

I am trying to modify most of our data processing pipeline with `collapse`(mostly written in `dplyr`). And I ran into the problem with finding the right alternatives for the function `case_when` from `dplyr`. The following example actually worked due to the great design of flexibility and interactivity with the `collapse` object. But I wondered if there are ways in the `collapse` package to replace the `case_when` function with something else? In that way, it might boost the performance to another level. The recode method was not what I have in mind at this point.

```
library(tidyverse)
library(collapse)
x <- 1:50
tbl <- tibble(variable = x)
microbenchmark::microbenchmark(
  dplyr = tbl %>%
    mutate(
      cat = case_when(
        x %% 35 == 0 ~ "fizz buzz",
        x %% 5 == 0 ~ "fizz",
        x %% 7 == 0 ~ "buzz",
        TRUE ~ as.character(x)
      )
    ),
  collapse = tbl %>%
    ftransform(
      cat = case_when(
        x %% 35 == 0 ~ "fizz buzz",
        x %% 5 == 0 ~ "fizz",
        x %% 7 == 0 ~ "buzz",
        TRUE ~ as.character(x)
      )
    )
)
```

**Comment by NetZissou** [comment]
Also, is there a way for the function `ftransform` to refer to the variables during construction like `mutate`? I think right now I need to call the function two times which seems a bit redundant. 
```
tbl %>%
  mutate(
    y = x/10,
    logy = log(y)
  )

tbl %>%
  ftransform(
    y = x/10
  ) %>%
  ftransform(
    logy = log(y)
  )
```

**Comment by SebKrantz** [comment]
Hi, thank you for using *collapse*. There is `data.table::fcase`. *collapse* will never be a fully-fledged data manipulation tool (note the 'advanced' in the title, and no need from my perspective to reinvent state of the art code available in *data.table*). I will try however to provide a complete set of functionality to complement *data.table*, so that *data.table* gives you the fast joins, rolling stats, melting and casting, setorder and setcolorder, fifelse, fcase, nafill, setnafill etc... and *collapse* gives you the fast grouped and weighted statistics, advanced aggregation, data transformations, time series and panel data stuff and dplyr-like data manipulation functionality. 

Regarding the latter, I don't think it will be implemented because it requires a level of intelligence that would reduce speed. Note that this also does not work with base R:

```
# This fails
transform(mtcars,
    y = mpg/10,
    logy = log(y)
)

# This is closer to what ftransform does internally: Also fails, because you cannot evaluate this list at once. 
with(mtcars,
    list(y = mpg/10,
         logy = log(y))
)
```
In my opinion, it is precisely this kind of intelligence and over-doing it on lazy evaluation that makes *dplyr* slow.

**Comment by NetZissou** [comment]
Thank you for the quick response! I think when Hadley is designing dplyr the main focus would be on the beauty of data processing gramma. I have been using dplyr for such a long time that I kind of detached from the base R functionalities. It is time for me to move out of my comfort zone a bit now.
